

states_mapping = {
    'DTTO. CAPITAL': 'Distrito Capital',
    'EDO. LA GUAIRA': 'La Guaira',
    'EDO. CARABOBO': 'Carabobo',
    'EDO. FALCON': 'Falcón',
    'EDO. TACHIRA': 'Táchira',
    'EDO. COJEDES': 'Cojedes',
    'EDO. APURE': 'Apure',
    'EDO. SUCRE': 'Sucre',
    'EDO. GUARICO': 'Guárico',
    'EDO. DELTA AMAC': 'Delta Amacuro',
    'EDO. MERIDA': 'Mérida',
    'EDO. ANZOATEGUI': 'Anzoátegui',
    'EDO. PORTUGUESA': 'Portuguesa',
    'EDO. LARA': 'Lara',
    'EDO. TRUJILLO': 'Trujillo',
    'EDO. ZULIA': 'Zulia',
    'EDO. MIRANDA': 'Miranda',
    'EDO. BARINAS': 'Barinas',
    'EDO. YARACUY': 'Yaracuy',
    'EDO. MONAGAS': 'Monagas',
    'EDO.NVA.ESPARTA': 'Nueva Esparta',
    'EDO. ARAGUA': 'Aragua',
    'EDO. BOLIVAR': 'Bolívar',
    'EDO. AMAZONAS': 'Amazonas'
}

municipalities_mapping = {
    'MP. MICHELENA': 'Michelena',
    'MP. PIAR': 'Piar',
    'MP. SANTOS MARQUINA': 'Santos Marquina',
    'MP. AGUASAY': 'Aguasay',
    'MP. URUMACO': 'Urumaco',
    'MP. J.V. CAMPO ELIAS': 'Juan Vicente Campo Elías',
    'MP. TOVAR': 'Tovar',
    'MP. CARLOS ARVELO': 'Carlos Arvelo',
    'MP. MONTE CARMELO': 'Monte Carmelo',
    'MP. LOS TAQUES': 'Los Taques',
    'MP. CAMAGUAN': 'Camaguan',
    'MP. OSPINO': 'Ospino',
    'MP. SAN DIEGO': 'San Diego',
    'MP. SOSA': 'Sosa',
    'MP.ROSARIO DE PERIJA': 'Rosario de Perija',
    'MP. LOS SALIAS': 'Los Salías',
    'MP. ANZOATEGUI': 'Anzoátegui',
    'MP. MANEIRO': 'Maneiro',
    'MP. ANACO': 'Anaco',
    'MP. MARACAIBO': 'Maracaibo',
    'MP. MONAGAS': 'Monagas',
    'MP. ARISMENDI': 'Arismendi',
    'MP. ZARAZA': 'Pedro Zaraza',
    'MP. ACHAGUAS': 'Achaguas',
    'MP. EL HATILLO': 'El Hatillo',
    'MP. GUACARA': 'Guacara',
    'MP. MOTATAN': 'Motatan',
    'MP. ARISTIDES BASTID': 'Arístides Bastidas',
    'MP. SEBORUCO': 'Seboruco',
    'MP. MACHIQUES DE P': 'Machiques de Perija',
    'MP.S JUAN CAPISTRANO': 'San Juan de Capistrano',
    'MP. PEÑA': 'Peña',
    'MP. PEDRO GUAL': 'Pedro Gual',
    'MP. FERNANDEZ FEO': 'Fernández Feo',
    'MP. JOSE R REVENGA': 'José Rafael Revenga',
    'MP. CAPACHO VIEJO': 'Libertad',
    'MP.OCUMARE D L COSTA': 'Ocumare de la Costa de Oro',
    'MP. SAN FERNANDO': 'San Fernando',
    'MP. IRIBARREN': 'Iribarren',
    'MP. MEJIA': 'Mejía',
    'MP. ARICAGUA': 'Aricagua',
    'MP. MATURIN': 'Maturín',
    'MP. ARAURE': 'Araure',
    'MP. PEDERNALES': 'Pedernales',
    'MP. SANTIAGO MARIÑO': 'Santiago Mariño',
    'MP. JESUS M SEMPRUN': 'Jesús María Semprum',
    'MP. MC GREGOR': 'Sir Arthur Mc Gregor',
    'MP. TINACO': 'Tinaco',
    'MP. LIBERTAD': 'Libertad',
    'MP. ARAGUA': 'Aragua',
    'MP. PUNCERES': 'Punceres',
    'MP. URACHICHE': 'Urachiche',
    'MP. BEJUMA': 'Bejuma',
    'MP. EZEQUIEL ZAMORA': 'Ezequiel Zamora',
    'MP. LA CAÑADA DE U.': 'La Cañada de Urdaneta',
    'MP. TUREN': 'Turen',
    'MP. CACIQUE MANAURE': 'Cacique Manaure',
    'MP. RAFAEL URDANETA': 'Rafael Urdaneta',
    'MP. SAN JOAQUIN': 'San Joaquín',
    'MP. S MARIA DE IPIRE': 'Santa María de Ipire',
    'MP. ARZOBISPO CHACON': 'Arzobispo Chacón',
    'MP. RANGEL': 'Rangel',
    'MP. COCOROTE': 'Cocorote',
    'MP. JOSE ANGEL LAMAS': 'José Ángel Lamas',
    'MP. SIMON BOLIVAR': 'Simón Bolívar',
    'MP. ROJAS': 'Rojas',
    'MP. A JOSE DE SUCRE': 'Antonio José de Sucre',
    'MP. JOSE FELIX RIBAS': 'José Félix Ribas',
    'MP. BOCONO': 'Bocono',
    'MP. ANTONIO ROMULO C': 'Antonio Rómulo Costa',
    'MP. DABAJURO': 'Dabajuro',
    'MP. CARIRUBANA': 'Carirubana',
    'MP. MARIÑO': 'Mariño',
    'MP.CARDENAL QUINTERO': 'Cardenal Quintero',
    'MP. FALCON': 'Falcón',
    'MP. JOSE M. VARGAS': 'José María Vargas',
    'MP.VALMORE RODRIGUEZ': 'Valmore Rodríguez',
    'MP. CARACCIOLO PARRA': 'Caracciolo Parra Olmedo',
    'MP. CARIPE': 'Caripe',
    'MP. RICAURTE': 'Ricaurte',
    'MP. JUAN JOSE MORA': 'Juan José Mora',
    'MP. SAMUEL MALDONADO': 'Samuel Darío Maldonado',
    'MP.PADRE PEDRO CHIEN': 'Padre Pedro Chien',
    'MP. ZEA': 'Zea',
    'MP.FRANCISCO LINARES': 'Francisco Linares Alcántara',
    'MP. SUCRE': 'Sucre',
    'MP. ESTELLER': 'Esteller',
    'MP. ESCUQUE': 'Escuque',
    'MP. MELLADO': 'Julián Mellado',
    'MP. MONTALBAN': 'Montalbán',
    'MP. FRANCISCO J PULG': 'Francisco Javier Pulgar',
    'MP. SILVA': 'Silva',
    'MP. MUÑOZ': 'Muñoz',
    'MP. ANDRES BELLO': 'Andrés Bello',
    'MP. ACEVEDO': 'Acevedo',
    'MP. L/DIEGO BAUTISTA': 'Diego Bautista Urbaneja',
    'MP. SAN CRISTOBAL': 'San Cristóbal',
    'MP. INDEPENDENCIA': 'Independencia',
    'MP. JIMENEZ': 'Jiménez',
    'MP.JULIO CESAR SALAS': 'Julio Cesar Salas',
    'MP.S JOSE DE GUARIBE': 'San José de Guaribe',
    'MP. SAN FRANCISCO': 'San Francisco',
    'MP. PLAZA': 'Plaza',
    'MP. BARALT': 'Baralt',
    'MP. GUASIMOS': 'Guasimos',
    'MP. MONTES': 'Montes',
    'MP. COLON': 'Colon',
    'MP. SANTA ANA': 'Santa Ana',
    'MP. RAFAEL RANGEL': 'Rafael Rangel',
    'MP. COLINA': 'Colina',
    'MP. VEROES': 'Veroes',
    'MP. AUTONOMO TINAQUI': 'Tinaquillo',
    'MP. BLVNO LIBERTADOR': 'Libertador',
    'MP. NIRGUA': 'Nirgua',
    'MP. BIRUACA': 'Biruaca',
    'MP. MONS. ITURRIZA': 'Monseñor Iturriza',
    'MP. INFANTE': 'Leonardo Infante',
    'MP. PAZ CASTILLO': 'Paz Castillo',
    'MP. CHACAO': 'Chacao',
    'MP. CAJIGAL': ['Juan Manuel Cajigal', 'Cajigal'],
    'MP. URACOA': 'Uracoa',
    'MP. BARUTA': 'Baruta',
    'MP. PEÑALVER': 'Fernando de Peñalver',
    'MP. TRUJILLO': 'Trujillo',
    'MP. ANTONIO PINTO S.': 'Antonio Pinto Salinas',
    'MP. VALENCIA': 'Valencia',
    'MP. GUANTA': 'Guanta',
    'MP. PAEZ': 'Páez',
    'MP. CORDOBA': 'Córdoba',
    'MP. SIFONTES': 'Sifontes',
    'MP. OBISPOS': 'Obispos',
    'MP. TULIO F CORDERO': 'Tulio Febres Cordero',
    'MP. SANTOS MICHELENA': 'Santos Michelena',
    'MP. RIBAS': 'José Félix Ribas',
    'MP. UNION': 'Unión',
    'MP. CRESPO': 'Crespo',
    'MP. LOBATERA': 'Lobatera',
    'MP.GENARO BOCONOITO': 'San Genaro de Boconoito',
    'MP. MARA': 'Mara',
    'MP. CEDEÑO': 'Cedeño',
    'MP. ROMULO GALLEGOS': 'Rómulo Gallegos',
    'MP.OB. RAMOS DE LORA': 'Obispo Ramos de Lora',
    'MP. PETIT': 'Petit',
    'MP. CARRIZAL': 'Carrizal',
    'MP. PAPELON': 'Papelón',
    'MP. CARACHE': 'Carache',
    'MP. BARINAS': 'Barinas',
    'MP. PEDRAZA': 'Pedraza',
    'MP. FREITES': 'Pedro María Freites',
    'MP. GUANIPA': 'San José de Guanipa',
    'MP.VILLALBA(I.COCHE)': 'Villalba',
    'MP. M.JOSE V DE UNDA': 'Monseñor José Vicente de Unda',
    'MP. MARIO B IRAGORRY': 'Mario Briceño Iragorri',
    'MP. VARGAS': 'Vargas',
    'MP. MAUROA': 'Mauroa',
    'MP. LIMA BLANCO': 'Lima Blanco',
    'MP. CRUZ PAREDES': 'Cruz Paredes',
    'MP. SANTA BARBARA': 'Santa Barbara',
    'MP. PAMPAN': 'Pampan',
    'MP. PUERTO CABELLO': 'Puerto Cabello',
    'MP. GUANARITO': 'Guanarito',
    'MP. CAMATAGUA': 'Camatagua',
    'MP. PUEBLO LLANO': 'Pueblo Llano',
    'MP. EL SOCORRO': 'El Socorro',
    'MP. VALERA': 'Valera',
    'MP. BENITEZ': 'Benítez',
    'MP. SANTA ROSALIA': 'Santa Rosalía',
    'MP. BRION': 'Brión',
    'MP. ACOSTA': 'Acosta',
    'MP. GRAN SABANA': 'Gran Sabana',
    'MP. PALAVECINO': 'Palavecino',
    'MP. GUANARE': 'Guanare',
    'MP.JOSE ANTONIO PAEZ': 'José Antonio Páez',
    'MP. MANUEL MONGE': 'Manuel Monge',
    'MP. ALBERTO ARVELO T': 'Alberto Arvelo Torrealba',
    'MP. LOS GUAYOS': 'Los Guayos',
    'MP. LANDER': 'Lander',
    'MP. SANTA RITA': 'Santa Rita',
    'MP. TOCOPERO': 'Tocopero',
    'MP.S RAFAEL DE ONOTO': 'San Rafael de Onoto',
    'MP. EL CALLAO': 'El Callao',
    'MP. TUCUPITA': 'Tucupita',
    'MP. GARCIA DE HEVIA': 'García de Hevia',
    'MP. CABIMAS': 'Cabimas',
    'MP. ANDRES MATA': 'Andrés Mata',
    'MP. MIRANDA': ['Francisco de Miranda', 'Miranda'],
    'MP. VALDEZ': 'Valdez',
    'MP. SAN JUDAS TADEO': 'San Judas Tadeo',
    'MP. PAMPANITO': 'Pampanito',
    'MP. CAMPO ELIAS': 'Campo Elías',
    'MP. LA CEIBA': 'La Ceiba',
    'MP. JACURA': 'Jacura',
    'MP. BLVNO DE ANGOSTU': 'Bolivariano Angostura',
    'MP. RIBERO': 'Ribero',
    'MP. GIRARDOT': 'Girardot',
    'MP. PEDRO CAMEJO': 'Pedro Camejo',
    'MP. CAPACHO NUEVO': 'Independencia',
    'MP. ALBERTO ADRIANI': 'Alberto Adriani',
    'MP. J.F.MARQUEZ C.': 'José Felipe Márquez Cañizal',
    'MP.PEDRO MARIA UREÑA': 'Pedro María Ureña',
    'MP. JUSTO BRICEÑO': 'Justo Briceño',
    'MP. PALMASOLA': 'Palmasola',
    'MP. TORBES': 'Torbes',
    'MP. ANGOSTURA DEL OR': 'Angostura del Orinoco',
    'MP. BRUZUAL': ['Manuel Ezequiel Bruzual', 'Bruzual'],
    'MP. CANDELARIA': 'Candelaria',
    'MP. AGUA BLANCA': 'Agua Blanca',
    'MP. PAO S J BAUTISTA': 'Pao de San Juan Bautista',
    'MP. BERMUDEZ': 'Bermúdez',
    'MP. ZAMORA': ['Zamora', 'Ezequiel Zamora'],
    'MP. LAGUNILLAS': 'Lagunillas',
    'MP. JESUS E LOSSADA': 'Jesús Enrique Lossada',
    'MP. CRUZ S ACOSTA': 'Cruz Salmerón Acosta',
    'MP. BUROZ': 'Buroz',
    'MP. PIRITU': 'Piritu',
    'MP. ROSCIO': 'Roscio',
    'MP. CARONI': 'Caroní',
    'MP. GARCIA': 'García',
    'MP.ANTOLIN DEL CAMPO': 'Antolín del Campo',
    'MP. PANAMERICANO': 'Panamericano',
    'MP. SAN FELIPE': 'San Felipe',
    'MP. URDANETA': 'Urdaneta',
    'MP. DIEGO IBARRA': 'Diego Ibarra',
    'MP. SAN CASIMIRO': 'San Casimiro',
    'MP. BUCHIVACOA': 'Buchivacoa',
    'MP. CARVAJAL': 'Francisco del Carmen Carvajal',
    'MP. JUAN JOSE RONDON': 'Las Mercedes',
    'MP. LA TRINIDAD': 'La Trinidad',
    'MP. DIAZ': 'Díaz',
    'MP. ATURES': 'Autónomo Atures',
    'MP. AYACUCHO': 'Ayacucho',
    'MP.SAN GERONIMO DE G': 'San Gerónimo de Guayabal',
    'MP. TORRES': 'Torres',
    'MP.PENIN. DE MACANAO': 'Macanao',
    'MP. MARCANO': 'Marcano',
    'MP. CARDENAS': 'Cárdenas',
    'MP. CASACOIMA': 'Casacoima',
    'MP. GOMEZ': 'Gómez',
    'MP. CATATUMBO': 'Catatumbo',
    'MP. ORTIZ': 'Ortiz',
    'MP. ANDRES E. BLANCO': 'Andrés Eloy Blanco',
    'MP. ANDRES E BLANCO': 'Andrés Eloy Blanco',
    'MP. JUNIN': 'Junín',
    'MP. FCO DE MIRANDA': 'Francisco de Miranda',
    'MP. LIBERTADOR': 'Libertador',
    'MP. MORAN': 'Moran',
    'MP. INDIGENA BLVNO G': 'Indígena Bolivariano Guajira',
    'MP. ANTONIO DIAZ': 'Antonio Díaz',
    'MP. PADRE NOGUERA': 'Padre Noguera',
    'MP. FEDERACION': 'Federación',
    'MP. RIVAS DAVILA': 'Rivas Dávila',
    'MP. SAN SEBASTIAN': 'San Sebastián',
    'MP. URIBANTE': 'Uribante',
    'MP. SOTILLO': ['Juan Antonio Sotillo', 'Sotillo'],
    'MP.S RAFAEL CARVAJAL': 'San Rafael de Carvajal',
    'MP. SIMON RODRIGUEZ': 'Simón Rodríguez',
    'MP. NAGUANAGUA': 'Naguanagua',
    'MP. JUAN GERMAN ROSC': 'Juan Germán Roscio',
    'MP. CHAGUARAMAS': 'Chaguaramas',
    'MP. JAUREGUI': 'Jáuregui',
    'MP. BOLIVAR': ['Simón Bolívar', 'Bolívar'],
    'MP. TUBORES': 'Tubores',
    'MP. GUARAQUE': 'Guaraque',
    'MP. CRISTOBAL ROJAS': 'Cristóbal Rojas',
    'MP. GUAICAIPURO': 'Bolivariano Guaicaipuro'
}

parroquias_mapping = {
    'CM. MARIGUITAR': 'Bolívar',
    'PQ. DIVINA PASTORA': 'Divina Pastora',
    'PQ. ADICORA': 'Adícora',
    'CM. BOCONOITO': 'San Genaro de Boconoito',
    'PQ. CAPADARE': 'Capadare',
    'PQ. GUARAMACAL': 'Guaramacal',
    'PQ. ENCONTRADOS': 'Encontrados',
    'PQ. MONTES DE OCA': 'Montes de Oca',
    'PQ. GUAJIRO': 'Guajiro',
    'PQ. CORDOBA': 'Córdoba',
    'CM. NUEVA BOLIVIA': 'Tulio Febres Cordero',
    'PQ.TRINIDAD DE LA CAPILLA': 'Trinidad de la Capilla',
    'PQ. AGUIRRE': 'Aguirre',
    'PQ. FLOR DE PATRIA': 'Flor de Patria',
    'PQ. CHURUGUARA': 'Churuguara',
    'PQ. LA CONCORDIA': 'La Concordia',
    'PQ. PIO TAMAYO': 'Pío Tamayo',
    'PQ. PIRITU': 'Píritu',
    'PQ. PUNTA DE PIEDRAS': 'Punta de Piedras',
    'PQ. SAN MARTIN DE PORRES': 'San Martín de Porres',
    'C.M. MATURIN': 'Maturín',
    'PQ. SABANA GRANDE': 'Sabana Grande',
    'PQ. LOS CAPRICHOS': 'Los Caprichos',
    'PQ. MOSQUEY': 'Mosquey',
    'PQ. CANDELARIA': 'Candelaria',
    'PQ. CHIQUINQUIRA': 'Chiquinquirá',
    'PQ. ALTAGRACIA DE ORITUCO': 'Altagracia de Orituco',
    'PQ. ALTAGRACIA DE LA M': 'Altagracia de la Montaña',
    'PQ. EL PAO': 'El Pao',
    'PQ. MAPARARI': 'Mapararí',
    'PQ. CARLOS SOUBLETTE': 'Carlos Soublette',
    'CM. EL PLAYON': 'Santa Rosalía',
    'PQ. PAMPAN': 'Pampán',
    'PQ. CANTAGALLO': 'Cantagallo',
    'PQ. BARTOLOME SALOM': 'Bartolomé Salom',
    'PQ. TICOPORO': 'Ticoporo',
    'PQ. TAMARE': 'Tamare',
    'PQ. JACURA': 'Jacura',
    'PQ. MUCURUBA': 'Mucurubá',
    'PQ. FLORIDA': 'Florida',
    'PQ. PULIDO MENDEZ': 'Pulido Méndez',
    'PQ. URAMA': 'Urama',
    'CM. BAILADORES': 'Rivas Dávila',
    'PQ. LA PASTORA': 'La Pastora',
    'PQ. NAIGUATA': 'Naiguatá',
    'PQ. SAN RAFAEL DE ORITUCO': 'San Rafael de Orituco',
    'PQ. MIRANDA': 'Miranda',
    'CM. SANTA ANA': ['Santa Ana', 'Gómez'],
    'PQ. CECILIO ACOSTA': 'Cecilio Acosta',
    'PQ. AREVALO GONZALEZ': 'Arévalo González',
    'PQ. MORUY': 'Moruy',
    'CM. TARIBA': 'Cárdenas',
    'PQ. BOCA DE UCHIRE': 'San Juan de Capistrano',
    'PQ. JALISCO': 'Jalisco',
    'PQ. RIO CHICO': 'Río Chico',
    'CM. JUAN VICENTE BOLIVAR': 'Juan Vicente Bolívar y Ponte',
    'PQ. 23 DE ENERO': '23 de Enero',
    'CM. GUASIPATI': 'Roscio',
    'CM.SAN RAFAEL DEL PIÑAL': 'Fernández Feo',
    'PQ. CONSTITUCION': 'Constitución',
    'PQ. EL CHAPARRO': 'Sir Arthur Mc Gregor',
    'PQ. PQ AUGUSTO MIJARES': 'Augusto Mijares',
    'PQ. LA ROSA': 'La Rosa',
    'PQ. M.ARTURO CELESTINO A': 'Monseñor Arturo Celestino Álvarez',
    'PQ. EL RASTRO': 'El Rastro',
    'PQ. BIDEAU': 'Bideau',
    'PQ. QUESERAS DEL MEDIO': 'Queseras del Medio',
    'PQ. BIRUACA': 'Biruaca',
    'PQ. LA PALMITA': 'La Palmita',
    'PQ. SAN CAMILO': 'San Camilo',
    'PQ. AGUA SANTA': 'Agua Santa',
    'PQ. LECHERIAS': 'Diego Bautista Urbaneja',
    'PQ.SAN JOSE DE BARLOVENTO': 'San José de Barlovento',
    'PQ. BOCA DE AROA': 'Boca de Aroa',
    'PQ. EL CAFE': 'El Café',
    'PQ. LIBERTAD': 'Libertad',
    'PQ. LA PICA': 'La Pica',
    'PQ.GRAN MARISCAL': 'Gran Mariscal los Altos de Sucre',
    'PQ. CABIMBU': 'Cabimbú',
    'PQ. JUAN GERMAN ROSCIO': 'Juan Germán Roscio',
    'PQ. SAN ANTONIO DE IRAPA': 'San Antonio de Irapa',
    'PQ. EL AMPARO': 'El Amparo',
    'PQ. NUEVA ARCADIA': 'Nueva Arcadia',
    'PQ. JUAREZ': 'Juárez',
    'PQ. MARIANO PARRA LEON': 'Mariano Parra León',
    'PQ. FILAS DE MARICHE': 'Filas de Mariches',
    'CM. TIMOTES': 'Miranda',
    'PQ. ANA MARIA CAMPOS': 'Ana María Campos',
    'PQ. ARAGUITA': 'Araguita',
    'PQ. LA PAZ': 'La Paz',
    'PQ. ANACO': 'Anaco',
    'PQ. SAN JOAQUIN': 'San Joaquín',
    'PQ. SABANA DE PIEDRA': 'Sabana de Piedra',
    'PQ. MONTALBAN': 'Montalbán',
    'PQ. ARAYA': 'Araya',
    'PQ. MONSEÑOR JAUREGUI': 'Monseñor Jáuregui',
    'PQ. ZAZARIDA': 'Zazarida',
    'PQ. VALERITA': 'Valerita',
    'PQ. SIQUISIQUE': 'Siquisique',
    'PQ. BRAMON': 'Bramón',
    'PQ. GUIRIA': 'Guiria',
    'PQ. ALMIRANTE LUIS BRION': 'Almirante Luis Brión',
    'CM. CARIPE': 'Caripe',
    'PQ. CURIEPE': 'Curiepe',
    'PQ. TINTORERO': 'Tintorero',
    'PQ. SAN LORENZO': 'San Lorenzo',
    'PQ. DALLA COSTA': 'Dalla Costa',
    'PQ. UVENCIO A VELASQUEZ': 'Uvencio Antonio Velásquez',
    'PQ. LA AGUADITA': 'La Aguadita',
    'PQ.CARACCIOLO PARRA PEREZ': 'Caracciolo Parra Pérez',
    'PQ. CURIMAGUA': 'Curimagua',
    'CM. NIRGUA': 'Nirgua',
    'PQ. BOCA DE GRITA': 'Boca de Grita',
    'PQ. CASTAÑEDA': 'Castañeda',
    'PQ. NORTE': 'Norte',
    'PQ. CAPAYA': 'Capaya',
    'CM. YARITAGUA': 'Peña',
    'PQ. UDON PEREZ': 'Udón Pérez',
    'PQ. U LOS GUAYOS': 'Los Guayos',
    'PQ. OCUMARE DE LA COSTA': 'Ocumare de la Costa de Oro',
    'PQ. GUARDATINAJAS': 'Guardatinajas',
    'PQ. JUSEPIN': 'Jusepín',
    'CM. SAN JOSE DE BOLIVAR': 'San José de Bolívar',
    'PQ. EMILIO C. GUERRERO': 'Emilio Constantino Guerrero',
    'PQ. JOSE BERNARDO DORANTE': 'Cabo José Dorante',
    'PQ. IGNACIO BRICEÑO': 'Ignacio Briceño',
    'PQ. CHAGUARAMAS': 'Chaguaramas',
    'PQ. MESA DE LAS PALMAS': 'Mesa de Las Palmas',
    'PQ. CARABALLEDA': 'Caraballeda',
    'PQ. LA BEATRIZ': 'La Beatriz',
    'PQ. FRANCISCO FAJARDO': 'Francisco Fajardo',
    'PQ. ARNOLDO GABALDON': 'Arnoldo Gabaldón',
    'CM. RUBIO': 'Junín',
    'PQ. VALLE DE LA PASCUA': 'Valle de la Pascua',
    'PQ. SANTA CRUZ DE GUACAS': 'Santa Cruz de Guacas',
    'PQ. LA TOMA': 'La Toma',
    'PQ. GUZMAN GUILLERMO': 'Guzmán Guillermo',
    'PQ. POZUELOS': 'Pozuelos',
    'PQ. VIENTO FRESCO': 'Viento Fresco',
    'CM. SAN PABLO': 'Arístides Bastidas',
    'PQ. CORAZON DE JESUS': 'Corazón de Jesús',
    'CM. TOCOPERO': 'Tocopero',
    'PQ. SN DIEGO DE CABRUTICA': 'San Diego de Cabrutica',
    'CM. CIUDAD PIAR': 'Angostura',
    'PQ. JUAN IGNACIO MONTILLA': 'Juan Ignacio Montilla',
    'PQ. GUAIMARAL': 'Guaimaral',
    'CM. ARICAGUA': 'Aricagua',
    'PQ. EL GUAYABO': 'El Guayabo',
    'PQ. MAIQUETIA': 'Maiquetía',
    'CM. LOBATERA': 'Lobatera',
    'PQ. PLATANILLAL': 'Platanillal',
    'CM. CAICARA': 'Cedeño',
    'PQ. JOSE ANTONIO PAEZ': 'José Antonio Páez',
    'PQ. LEONCIO MARTINEZ': 'Leoncio Martínez',
    'PQ. YOCOIMA': 'Yocoima',
    'PQ. PIMPINELA': 'Pimpinela',
    'PQ. ADRIAN': 'Adrián',
    'PQ. PEDRO MARIA MORANTES': 'Pedro María Morantes',
    'PQ. RAFAEL RANGEL': 'Rafael Rangel',
    'PQ. RINCON HONDO': 'Rincón Hondo',
    'PQ. STA.CRUZ DE BUCARAL': 'Santa Cruz de Bucaral',
    'PQ. MONS. ARGIMIRO GARCIA': 'Monseñor Argimiro García',
    'PQ. SALOM': 'Salom',
    'PQ. CARDENAS': 'Cárdenas',
    'CM. SEBORUCO': 'Seboruco',
    'PQ. HILARIO LUNA Y LUNA': 'Hilario Luna y Luna',
    'PQ. MUCURITAS': 'Mucuritas',
    'PQ. PUNTA CARDON': 'Punta Cardón',
    'PQ. CEGARRA': 'Cegarra',
    'PQ. FRANCISCO DE MIRANDA': 'Francisco de Miranda',
    'CM. MUCUCHIES': 'Rangel',
    'CM. QUENIQUEA': 'Sucre',
    'PQ. ELOY PAREDES': 'Eloy Paredes',
    'PQ. ANDRES ELOY BLANCO': 'Andrés Eloy Blanco',
    'PQ. CALABOZO': 'Calabozo',
    'PQ. EL MORRO DE PTO SANTO': 'El Morro de Puerto Santo',
    'PQ. IMATACA': 'Imataca',
    'PQ. JOSE CASANOVA GODOY': 'José Casanova Godoy',
    'PQ. INDEPENDENCIA': 'Independencia',
    'PQ. REYES VARGAS': 'Reyes Vargas',
    'PQ. DOMITILA FLORES': 'Domitila Flores',
    'PQ. PRESIDENTE PAEZ': 'Presidente Páez',
    'PQ. LEONARDO RUIZ PINEDA': 'Leonardo Ruiz Pineda',
    'PQ. EL CANTON': 'El Cantón',
    'PQ. EL SOMBRERO': 'El Sombrero',
    'PQ. SANTO DOMINGO': 'Santo Domingo',
    'CM. EL CALLAO': 'El Callao',
    'PQ. COCOLLAR': 'Cocollar',
    'PQ. MATASIETE': 'Matasiete',
    'PQ. OCUMARE DEL TUY': 'Ocumare del Tuy',
    'PQ. MORALITO': 'Moralito',
    'PQ. CATUARO': 'Catuaro',
    'CM. PIRITU': ['Píritu', 'Esteller'],
    'PQ. OBISPOS': 'Obispos',
    'PQ. OSUNA RODRIGUEZ': 'Osuna Rodríguez',
    'PQ. GUERRERA ANA SOTO': 'Juan de Villegas',
    'CM. GUARAQUE': 'Guaraque',
    'PQ. ALTAGRACIA': 'Altagracia',
    'CM. SAN CASIMIRO': 'San Casimiro',
    'CM. VALLE ESP SANTO': 'García',
    'PQ. ARISMENDI': 'Arismendi',
    'PQ. MACARAO': 'Macarao',
    'PQ. SAN BLAS': 'San Blas',
    'PQ. MONSEÑOR CARRILLO': 'Monseñor Carrillo',
    'PQ. AGUA LINDA': 'Agua Linda',
    'PQ. PEDRO JOSE OVALLES': 'Pedro José Ovalles',
    'CM. SAN JUAN BAUTISTA': 'Díaz',
    'PQ. SAN PABLO': 'San Pablo',
    'PQ. YAGUARAPARO': 'Yaguaraparo',
    'PQ. LAS MINAS DE BARUTA': 'Las Minas de Baruta',
    'PQ. PIÑANGO': 'Piñango',
    'PQ. LA VEGA': 'La Vega',
    'PQ. TUCACAS': 'Tucacas',
    'PQ. COQUIVACOA': 'Coquivacoa',
    'PQ. COJEDES': 'Cojedes',
    'PQ. MACHURUCUTO': 'Machurucuto',
    'PQ. CIUDAD DE NUTRIAS': 'Ciudad de Nutrias',
    'PQ. EL JARILLO': 'El Jarillo',
    'PQ. LOS TEQUES': 'Los Teques',
    'PQ. SAN FRANCISCO DE CARA': 'San Francisco de Cara',
    'CM. CAPACHO NUEVO': 'Independencia',
    'CM. ONOTO': 'Juan Manuel Cajigal',
    'PQ. SAN JOSE DE UNARE': 'San José de Unare',
    'PQ. VIRGEN DEL VALLE': 'Virgen del Valle',
    'PQ. CAÑO EL TIGRE': 'Caño El Tigre',
    'PQ. ROMAN CARDENAS': 'Román Cárdenas',
    'PQ. BOBURES': 'Bobures',
    'CM. SANTA BARBARA': 'Santa Bárbara',
    'CM. LAS MESAS': 'Antonio Rómulo Acosta',
    'PQ. NAGUANAGUA': 'Naguanagua',
    'PQ. JOAQUIN CRESPO': 'Joaquín Crespo',
    'PQ. LA PETROLEA': 'La Petrolea',
    'PQ. CARACHE': 'Carache',
    'PQ. SAN AGUSTIN': 'San Agustín',
    'PQ. ADAURE': 'Adaure',
    'PQ. MAGDALENO': 'Magdaleno',
    'PQ. CATEDRAL': 'Catedral',
    'PQ. CUMANACOA': 'Cumanacoa',
    'PQ. CAMPO CLARO': 'Campo Claro',
    'CM. SAN MATEO': ['Libertad', 'Bolívar'],
    'PQ. RIVAS BERTI': 'Rivas Berti',
    'PQ. PARACOTOS': 'Paracotos',
    'PQ. YACAMBU': 'Yacambú',
    'CM. TABAY': 'Santos Marquina',
    'PQ. BARUTA': 'Nuestra Señora del Rosario de Baruta',
    'PQ. CHIRICA': 'Chirica',
    'PQ. BURBUSAY': 'Burbusay',
    'PQ. VICENTE FUENTES': 'Vicente Fuentes',
    'PQ. MACAPO': 'Macapo',
    'PQ. CIPRIANO CASTRO': 'Cipriano Castro',
    'PQ. PUERTO SANTO': 'Puerto Santo',
    'CM. URACOA': 'Uracoa',
    'PQ. SAN JUAN DE PAYARA': 'San Juan de Payara',
    'CM. ACARIGUA': 'Páez',
    'PQ. JADACAQUIVA': 'Jadacaquiva',
    'PQ. SANTA RITA': 'Santa Rita',
    'PQ. LUIS B. PRIETO F.': 'Luis Beltrán Prieto Figueroa',
    'PQ. GUACHARA': 'Guachara',
    'CM. ARAPUEY': 'Rómulo Gallegos',
    'PQ. GUATIRE': 'Guatire',
    'CM. YUMARE': 'Manuel Monge',
    'PQ. RENDON': 'Rendón',
    'CM. LA TENDIDA': 'Samuel Darío Maldonado',
    'PQ. VENEZUELA': 'Venezuela',
    'PQ. SANTA CRUZ DEL ZULIA': 'Santa Cruz del Zulia',
    'PQ. URDANETA': 'Urdaneta',
    'CM. BARBACOAS': 'Urdaneta',
    'PQ. EL YAGUAL': 'El Yagual',
    'PQ. EL HATILLO': 'El Hatillo',
    'PQ. CARLOS QUEVEDO': 'Carlos Quevedo',
    'PQ. SABANETA': 'Sabaneta',
    'PQ. LOS GUASIMITOS': 'Guasimitos',
    'PQ. ARIAS': 'Arias',
    'PQ. TRES ESQUINAS': 'Tres Esquinas',
    'PQ. LAS COCUIZAS': 'Las Cocuizas',
    'PQ. MERCEDES DIAZ': 'Mercedes Díaz',
    'PQ. CURIAPO': 'Curiapo',
    'PQ. ALTO BARINAS': 'Alto Barinas',
    'PQ. SAN JOSE DE TIZNADOS': 'San José de Tiznados',
    'PQ. PALMIRA': 'Palmira', 
    'PQ. TACARIGUA': ['Tacarigua', 'Tacarigua Central'],
    'CM. STA ELENA DE ARENALES': 'Obispo Ramos de Lora',
    'PQ. SAN FERNANDO': ['San Fernando de Apure', 'San Fernando'],
    'PQ. MADRE MA DE SAN JOSE': 'Madre María de San José',
    'CM. CHIVACOA': 'Bruzual',
    'PQ. GONZALO PICON FEBRES': 'Gonzalo Picón Febres',
    'PQ. GUASDUALITO': 'Guasdualito',
    'PQ. LA VENTA': 'La Venta',
    'PQ. JUAN RODRIGUEZ SUAREZ': 'Juan Rodríguez Suárez',
    'PQ. MANUEL PIAR': 'Manuel Piar',
    'CM. PUNTA DE PIEDRAS': 'Tubores',
    'PQ. BOCA DE CHAVEZ': 'Boca de Chávez',
    'PQ. PRESIDENTE BETANCOURT': 'Presidente Betancourt',
    'PQ. ONCE DE ABRIL': 'Once de Abril',
    'PQ. ESPINO': 'Espino',
    'PQ. SAN JOAQUIN DE NAVAY': 'San Joaquín de Navay',
    'PQ. CASIGUA': 'Casigua',
    'PQ. ALFREDO PACHECO M': 'Alfredo Pacheco Miranda',
    'PQ. VIRGEN DE LA COROMOTO': 'Virgen de la Coromoto',
    'CM. UREÑA': 'Pedro María Ureña',
    'PQ. FERNANDO GIRON TOVAR': 'Fernando Girón Tovar',
    'CM. AGUA BLANCA': 'Agua Blanca',
    'PQ. JUAN ANGEL BRAVO': 'Juan Ángel Bravo',
    'PQ. ESPINOZA LOS MONTEROS': 'Espinoza de los Monteros',
    'PQ. HECTOR AMABLE MORA': 'Héctor Amable Mora',
    'PQ. FRATERNIDAD': 'Fraternidad',
    'CM. PREGONERO': 'Uribante',
    'PQ. SAN SIMON': 'San Simón',
    'PQ. LAS ALHUACAS': 'Las Alhuacas',
    'PQ. JUAN BAUTISTA ARISMEN': 'Juan Bautista Arismendi',
    'PQ. MANUEL GUANIPA MATOS': 'Manuel Guanipa Matos',
    'PQ. QBDA. HONDA DE GUACHE': 'Quebrada Honda de Guache',
    'CM. PUNTA DE MATA': 'Ezequiel Zamora',
    'PQ. JAJO': 'Jajo',
    'CM. PAPELON': 'Papelón',
    'PQ. SUCRE': 'Sucre',
    'CM. FARRIAR': 'Veroes',
    'PQ. GUANTA': 'Guanta',
    'PQ. AGUSTIN CODAZZI': 'Simón Rodríguez',
    'PQ. CANELONES': 'Canelones',
    'CM. EL CONSEJO': 'José Rafael Revenga',
    'PQ. LAS PIEDRAS': 'Las Piedras',
    'PQ. MONTE CARMELO': 'Monte Carmelo',
    'PQ. SAN CARLOS DEL ZULIA': 'San Carlos del Zulia',
    'PQ. POTOSI': 'Potosí',
    'PQ. XAGUAS': 'Xaguas',
    'PQ. CRNEL. MARIANO PERAZA': 'Coronel Mariano Peraza',
    'PQ. MATRIZ': 'Matriz',
    'PQ. LAS DELICIAS': 'Las Delicias',
    'PQ. SANTA ISABEL': 'Santa Isabel',
    'PQ. GENERAL URDANETA': 'General Urdaneta',
    'PQ. ANTONIO N BRICEÑO': 'Antonio Nicolás Briceño',
    'PQ. EL BLANCO': 'El Blanco',
    'PQ. CARACCIOLO PARRA P': 'Caracciolo Parra Pérez',
    'PQ. BARIRO': 'Bariro',
    'PQ. SAN SEBASTIAN': 'San Sebastián',
    'CM. ZEA': 'Zea',
    'CM. UMUQUENA': 'San Judas Tadeo',
    'CM. STA CRUZ DE MORA': 'Pinto Salinas',
    'PQ. SAN BENITO': 'San Benito',
    'PQ. HERNANDEZ': 'Hernández',
    'PQ. DR. FCO. ROMERO LOBO': 'Dr. Francisco Romero Lobo',
    'CM. MICHELENA': 'Michelena',
    'PQ. CHICHIRIVICHE': 'Chichiriviche',
    'CM. CLARINES': 'Manuel Ezequiel Bruzual',
    'PQ. CAÑA DE AZUCAR': 'Caña de Azúcar',
    'PQ. LOS TACARIGUAS': 'Los Tacariguas',
    'CM. VILLA DE CURA': 'Ezequiel Zamora',
    'PQ. BOCA DE TOCUYO': 'Boca de Tocuyo',
    'CM. SANTA CRUZ': 'Jose Angel Lamas',
    'PQ. ORTIZ': 'Ortiz',
    'PQ. SAN JOSE DE SAGUAZ': 'San José de Saguaz',
    'PQ. SANTA CRUZ': 'Santa Cruz',
    'PQ. EL CUJI': 'El Cuji',
    'PQ. PANAMERICANA': 'Panamericana',
    'PQ. EL PILAR': 'El Pilar',
    'PQ. CABUDARE': 'Cabudare',
    'PQ. GOAIGOAZA': 'Goaigoaza',
    'PQ. TUCUPIDO': 'Tucupido',
    'PQ. EL LLANO': 'El Llano',
    'PQ. SAN JUAN DE LAS GALDO': 'San Juan de las Galdonas',
    'PQ. PAPARO': 'Páparo',
    'PQ. PUEBLO NUEVO DEL SUR': 'Pueblo Nuevo del Sur',
    'PQ. AYACUCHO': 'Ayacucho',
    'PQ. EL JUNQUITO': 'El Junquito',
    'PQ. BRUZUAL': 'Bruzual',
    'PQ. SABANA DE MENDOZA': 'Sabana de Mendoza',
    'PQ. SANTA BARBARA': 'Santa Bárbara',
    'PQ. CAMAGUAN': 'Camaguán',
    'PQ. PALOTAL': 'Palotal',
    'PQ. APURITO': 'Apurito',
    'PQ. CONCEPCION': 'Concepción',
    'PQ. ARAURIMA': 'Araurima',
    'CM. MIRIMIRE': 'San Francisco',
    'PQ. PARAPARA': 'Parapara',
    'PQ. AGUA CALIENTE': 'Agua Caliente',
    'PQ. ESCUQUE': 'Escuque',
    'PQ. ANDRES LINARES': 'Andrés Linares',
    'CM. LA FRIA': 'García de Hevia',
    'PQ. GUAYABAL': 'San Gerónimo de Guayabal',
    'PQ. MONTA¿A VERDE': 'Montaña Verde',
    'CM. CANAGUA': 'Arzobispo Chacón',
    'PQ. RAMON PERAZA': 'Ramón Peraza',
    'PQ. MARCIAL HERNANDEZ': 'Marcial Hernández',
    'PQ. PEDERNALES': 'Pedernales',
    'PQ. FRANCISCO J PULGAR': 'Francisco Javier Pulgar',
    'PQ. ANTONIO SPINETTI DINI': 'Antonio Spinetti Dini',
    'CM. JUAN GRIEGO': 'Marcano',
    'PQ.TACARIGUA DE LA LAGUNA': 'Tacarigua de la Laguna',
    'PQ. SAN ANTONIO': 'San Antonio',
    'PQ. EL JAGUITO': 'El Jaguito',
    'PQ. SAN FCO DE MACAIRA': 'San Francisco de Macaira',
    'PQ. RAUL CUENCA': 'Raúl Cuenca',
    'PQ. RODRIGUEZ DOMINGUEZ': 'Rodríguez Domínguez',
    'PQ. GUADARRAMA': 'Guadarrama',
    'PQ. EL DIVIDIVE': 'El Dividive',
    'PQ. GUARENAS': 'Guarenas',
    'PQ. MARHUANTA': 'Marhuanta',
    'PQ. JOSE CENOVIO URRIBARR': 'José Cenovio Urribarri',
    'PQ. PAEZ': 'Páez',
    'PQ. CASTOR NIEVES RIOS': 'Castor Nieves Ríos',
    'PQ. SAN MIGUEL': 'San Miguel',
    'PQ. BARAIVED': 'Baraived',
    'CM. TURMERO': 'Santiago Mariño',
    'PQ. LAS PEÑITAS': 'Las Peñitas',
    'PQ. STA RITA DE MANAPIRE': 'Santa Rita de Manapire',
    'PQ. JOSE G HERNANDEZ': 'José Gregorio Hernández',
    'PQ. JOSE DOMINGO RUS': 'José Domingo Rus',
    'PQ. LIBERTADOR': 'Libertador',
    'PQ. PUERTO DE NUTRIAS': 'Puerto de Nutrias',
    'PQ. JUDIBANA': 'Judibana',
    'PQ. ARAMENDI': 'Arismendi',
    'CM. CARIPITO': 'Bolívar',
    'PQ. ALBERTO ADRIANI': 'Alberto Adriani',
    'PQ. CODAZZI': 'Codazzi',
    'PQ. BERGANTIN': 'Bergantín',
    'PQ. LA SABANITA': 'La Sabanita',
    'PQ. ACEQUIAS': 'Acequias',
    'PQ. PAO DE ZARATE': 'Pao de Zárate',
    'PQ. JESUS M SEMPRUN': 'Jesús María Semprum',
    'PQ. LAS MAJADAS': 'Las Majadas',
    'PQ. LA APARICION': 'Aparición',
    'PQ. PAMPANITO': 'Pampanito',
    'PQ. SAN JOSE DE LA COSTA': 'San José de la Costa',
    'CM. SAN PEDRO DE COCHE': 'Villalba',
    'PQ. EL VALLE': 'El Valle',
    'PQ. LA CONCEPCION': ['La Concepción', 'Concepción'],
    'PQ. EMETERIO OCHOA': 'Emeterio Ochoa',
    'PQ. BOCA DEL PAO': 'Boca del Pao',
    'PQ. TACATA': 'Tacata',
    'PQ. CAPATARIDA': 'Capatárida',
    'PQ. CRISTOBAL COLON': 'Cristóbal Colón',
    'PQ. AMENODORO RANGEL LAMU': 'Amenodoro Rangel Lamus',
    'PQ. EL COROZO': 'El Corozo',
    'CM. LAS TEJERIAS': 'Santos Michelena',
    'PQ. SAN RAFAEL DE LAYA': 'San Rafael de Laya',
    'PQ. VALLE MORIN': 'Valle Morín',
    'PQ. LA URBANA': 'La Urbana',
    'PQ. LA DEMOCRACIA': 'La Democracia',
    'PQ. TUNAPUICITO': 'Tunapuicito',
    'PQ. EL MENE': 'El Mene',
    'PQ. BOCONO': 'Boconó',
    'PQ. CRISTOBAL MENDOZA': 'Cristóbal Mendoza',
    'PQ. ZEA': 'Zea',
    'PQ. CACHAMAY': 'Cachamay',
    'PQ. HIGUEROTE': 'Higuerote',
    'PQ. 5 DE JULIO': 'Cinco de Julio',
    'PQ. ORINOCO': 'Orinoco',
    'PQ. RAMON I MENDEZ': 'Ramón Ignacio Méndez',
    'PQ. MOROTURO': 'Moroturo',
    'CM. PUEBLO LLANO': 'Pueblo Llano',
    'PQ. ROMULO BETANCOURT': ['Don Rómulo Betancourt', 'Rómulo Betancourt'],
    'PQ. LA DOLORITA': 'La Dolorita',
    'CM. AGUASAY': 'Aguasay',
    'PQ. PARAUTE': 'Alonso de Ojeda',
    'PQ. JOSE NUCETE SARDI': 'José Nucete Sardi',
    'PQ. HUMOCARO ALTO': 'Humocaro Alto',
    'PQ. TRINIDAD SAMUEL': 'Trinidad Samuel',
    'PQ. CAMPO ELIAS': 'Campo Elías',
    'PQ. CARMEN DE CURA': 'Carmen de Cura',
    'PQ. SANTA ROSA': 'Santa Rosa',
    'PQ. SAGRARIO': 'Sagrario',
    'PQ. ALTA GUAJIRA': 'Alta Guajira',
    'PQ. CAPURI': 'Capurí',
    'CM. STA MARIA DE CAPARO': 'Padre Noguera',
    'CM. CAICARA DEL ORINOCO': 'Cedeño',
    'PQ. SANTA LUCIA': 'Santa Lucía',
    'CM. COLONIA TOVAR': 'Tovar',
    'PQ. AGUA SALADA': 'Agua Salada',
    'PQ. ARICAGUA': 'Aricagua',
    'CM. DABAJURO': 'Dabajuro',
    'PQ. BOLIVAR': 'Bolívar',
    'CM. YARACAL': 'Cacique Manaure',
    'CM. LAGUNILLAS': 'Sucre',
    'PQ. CARVAJAL': 'Carvajal',
    'PQ. LA SOLEDAD': 'La Soledad',
    'PQ. MENE DE MAUROA': 'Mene de Mauroa',
    'PQ. MAMO': 'Mamo',
    'CM. SANTA RITA': 'Francisco Linares Alcántara',
    'PQ. EL CAFETAL': 'El Cafetal',
    'PQ. CHIGUARA': 'Chiguará',
    'PQ. TOVAR': 'Tovar',
    'PQ. SAMAN DE GUERE': 'Samán de Guere',
    'PQ. BETIJOQUE': 'Betijoque',
    'PQ.BARTOLOME DE LAS CASAS': 'Bartolomé de las Casas',
    'PQ. SOSA': 'Sosa',
    'CM. TUCANI': 'Caracciolo Parra Olmedo',
    'PQ. MESA DE QUINTERO': 'Mesa de Quintero',
    'PQ.SAN RAFAEL PALO ALZADO': 'San Rafael de Palo Alzado',
    'PQ. SAN CRISTOBAL DE T': 'San Cristóbal de Torondoy',
    'PQ. GRANADOS': 'Granados',
    'PQ. CHORRERON': 'Chorrerón',
    'PQ. CIUDAD BOLIVIA': 'Ciudad Bolivia',
    'PQ. PADRE BARRAL': 'Padre Barral',
    'CM. PORLAMAR': 'Mariño',
    'PQ. BARRANCAS': 'Barrancas',
    'PQ. TEMERLA': 'Temerla',
    'PQ. CACUTE': 'Cacute',
    'PQ. CAIGUA': 'Caigua',
    'PQ. EL BAÑO': 'El Baño',
    'PQ. EL REAL': 'El Real',
    'PQ. MARIANO PICON SALAS': 'Mariano Picón Salas',
    'PQ. NARICUAL': 'Naricual',
    'PQ. BOQUERON': 'Boquerón',
    'PQ. ZABALA': 'Zabala',
    'PQ. LA PUERTA': 'La Puerta',
    'PQ. LA LUZ': 'La Luz',
    'PQ. MORON': 'Morón',
    'PQ. SAN JOSE DE PERIJA': 'San José de Perijá',
    'CM. ARAURE': 'Araure',
    'PQ. TINAQUILLO': 'Tinaquillo',
    'PQ. SAN ISIDRO LABRADOR': 'San Isidro Labrador',
    'PQ. EL CHARAL': 'El Charal',
    'PQ. RIO SECO': 'Río Seco',
    'PQ. CAZORLA': 'Cazorla',
    'PQ. SAN ANTONIO LOS ALTOS': 'San Antonio de Los Altos',
    'PQ.MCL.ANTONIO J DE SUCRE': 'Mariscal Antonio José de Sucre',
    'PQ. TERESEN': 'Teresen',
    'PQ. ARISTIDES CALVANI': 'Arístides Calvani',
    'PQ. ANTIMANO': 'Antímano',
    'PQ. EL CALVARIO': 'El Calvario',
    'PQ. PUNTA GORDA': 'Punta Gorda',
    'PQ. GUARAUNOS': 'Guaraunos',
    'CM. PARIAGUAN': 'Francisco de Miranda',
    'PQ. BARI': 'Bari',
    'CM. BORAURE': 'La Trinidad',
    'PQ. UNIVERSIDAD': 'Universidad',
    'PQ. JORGE HERNANDEZ': 'Jorge Hernández',
    'PQ. CHACAO': 'Chacao',
    'PQ. ROMULO GALLEGOS': 'Rómulo Gallegos',
    'PQ. YAGUA': 'Yagua',
    'PQ. MANUEL P FAJARDO': 'Manuel Palacio Fajardo',
    'CM. VILLA BRUZUAL': 'Turén',
    'PQ. MARIA C PALACIOS': 'María de la Concepción Palacios Blanco',
    'PQ. EL CARITO': 'El Carito',
    'PQ. UNARE': 'Unare',
    'PQ. URICA': 'Úrica',
    'CM. GUANARITO': 'Guanarito',
    'PQ. LAS GUACAMAYAS': 'Las Guacamayas',
    'PQ. GERONIMO MALDONADO': 'Gerónimo Maldonado',
    'PQ. VALLE GUANAPE': 'Francisco del Carmen Carvajal',
    'PQ. GUANAPE': 'Guanape',
    'PQ. GUARATARO': 'Guarataro',
    'PQ. URIMARE': 'Urimare',
    'PQ. RAFAEL MARIA BARALT': 'Rafael María Baralt',
    'PQ. SN FERNANDO DEL GUAPO': 'San Fernando del Guapo',
    'PQ. MESA BOLIVAR': 'Mesa de Bolívar',
    'PQ. CECILIO ZUBILLAGA': 'Cecilio Zubillaga',
    'PQ. DORADAS': 'Doradas',
    'PQ. SANTA ANA': 'Santa Ana',
    'PQ. LOS TAQUES': 'Los Taques',
    'PQ. TAGUAY': 'Taguay',
    'PQ. ATAPIRIRE': 'Atapirire',
    'PQ. RIO CARIBE': 'Río Caribe',
    'PQ. GUAJIRA': 'Guajira',
    'PQ. COCHE': 'Coche',
    'PQ. ELEAZAR LOPEZ C': 'Eleazar López Contreras',
    'PQ. PARAISO DE SAN JOSE': 'Paraíso de San José',
    'PQ. FERNANDEZ PEÑA': 'Fernández Peña',
    'PQ. CHUAO': 'Chuao',
    'PQ. ASCENSION FARRERAS': 'Ascensión Farreras',
    'PQ. PEÑALVER': 'Peñalver',
    'PQ. AGUA LARGA': 'Agua Larga',
    'PQ. JOSE LEONARDO SUAREZ': 'José Leonardo Suárez',
    'PQ. GUARICO': 'Guárico',
    'PQ. EL BAUL': 'El Baúl',
    'PQ. RAFAEL URDANETA': 'Rafael Urdaneta',
    'PQ. ISAIAS MEDINA ANGARIT': 'Isaías Medina Angarita',
    'PQ. JUAN PABLO PEÑALOZA': 'Juan Pablo Peñaloza',
    'PQ. FLORENCIO RAMIREZ': 'Florencio Ramírez',
    'PQ. VALLES DE TUCUTUNEMO': 'Valles de Tucutunemo',
    'CM. PUERTO PIRITU': 'Fernando de Peñalver',
    'PQ. RAUL LEONI': 'Raúl Leoni los Puertos de Santa Fé',
    'PQ. GUACARA': 'Guacara',
    'PQ. BEJUMA': 'Bejuma',
    'PQ. SAN PEDRO': 'San Pedro',
    'PQ. THERMO MORALES': 'Thermo Morales',
    'PQ. SAN FCO. DE TIZNADOS': 'San Francisco de Tiznados',
    'PQ. IRAPA': 'Irapa',
    'PQ. GENERAL RIVAS': 'General Rivas',
    'PQ. UVERAL': 'Uveral',
    'PQ. MANUEL MANRIQUE': 'Manuel Manrique',
    'PQ. GRL/JEFE JOSE L SILVA': 'General en Jefe José Laurencio Silva',
    'PQ. SANTA INES': 'Santa Inés',
    'PQ. LA TRAMPA': 'La Trampa',
    'PQ. NICOLAS PULIDO': 'Nicolás Pulido',
    'PQ. CUNAVICHE': 'Cunaviche',
    'PQ. LIBERTAD DE COJEDES': 'Libertad de Cojedes',
    'CM. SAN ANT DEL TACHIRA': 'Bolívar',
    'PQ. JUAN MILLAN': 'Juan Millán',
    'CM. CAGUA': 'Sucre',
    'PQ. SIMON RODRIGUEZ': 'Simón Rodríguez',
    'CM. EL TIGRE': 'Miguel Otero Silva',
    'PQ.ELEAZAR LOPEZ CONTRERA': 'Eleazar López Contreras',
    'PQ. CANOABO': 'Canoabo',
    'PQ. CHAGUARAMAL': 'Chaguaramal',
    'PQ. MOTATAN': 'Motatan',
    'PQ. LA GUAIRA': 'La Guaira',
    'PQ. SAN JOSE': ['San José del Sur', 'San José'],
    'CM. SAN RAFAEL DE ONOTO': 'San Rafael de Onoto',
    'CM. CANTAURA': 'Pedro María Freites',
    'PQ. POZO VERDE': 'Pozo Verde',
    'PQ. MARABAL': 'Marabal',
    'CM. QUIRIQUIRE': 'Punceres',
    'PQ. ARAGUANEY': 'Araguaney',
    'PQ. LAS CALDERAS': 'Las Calderas',
    'PQ. URIBARRI': 'Urribarri',
    'PQ. GUIRIPA': 'Guiripa',
    'CM. COCOROTE': 'Cocorote',
    'PQ. MIGUEL PEÑA': 'Miguel Peña',
    'PQ. ACURIGUA': 'Acurigua',
    'CM. SABANA DE PARRA': 'José Antonio Páez',
    'PQ. MASPARRITO': 'Masparrito',
    'PQ. DOMINGO PEÑA': 'Domingo Peña',
    'PQ. VISTA HERMOSA': 'Vista Hermosa',
    'PQ. VILLA ROSA': 'Villa Rosa',
    'CM. INDEPENDENCIA': 'Independencia',
    'CM. BOCA DEL RIO': 'Península de Macanao',
    'PQ. SABANA DE UCHIRE': 'Sabana de Uchire',
    'PQ. AREO': 'Areo',
    'CM. COLON': 'Ayacucho',
    'PQ. EL PARAISO': 'El Paraíso',
    'CM. CAPACHO VIEJO': 'Libertad',
    'PQ. STA TERESA DEL TUY': 'Santa Teresa del Tuy',
    'PQ. CARICUAO': 'Caricuao',
    'PQ. ANTONIO DIAZ': 'Antonio Díaz',
    'PQ. GUANAGUANA': 'Guanaguana',
    'PQ. LA TOSCANA': 'La Toscana',
    'PQ. JOSE G. BASTIDAS': 'José Gregorio Bastidas',
    'PQ. EL GUAPO': 'El Guapo',
    'PQ. PUERTO CUMAREBO': 'Puerto Cumarebo',
    'PQ. CRISTO DE ARANZA': 'Cristo de Aranza',
    'PQ. MONS FELICIANO G': 'Monseñor Feliciano González',
    'PQ. EL GUACHARO': 'El Guácharo',
    'PQ. CUMBO': 'Cumbo',
    'PQ. LUIS DE VICENTE': 'Luis de Vicente',
    'PQ. CATIA LA MAR': 'Catia La Mar',
    'CM. BISCUCUY': 'Sucre',
    'PQ. EL DANTO': 'El Danto',
    'PQ. BUENA VISTA': 'Buena Vista',
    'PQ. LAS BRISAS': 'Las Brisas',
    'PQ. PASO REAL DE MACAIRA': 'Paso Real de Macaira',
    'PQ. TABASCA': 'Tabasca',
    'PQ. MITARE': 'Mitare',
    'PQ. MANUEL FELIPE RUGELES': 'Manuel Felipe Rugeles',
    'PQ. MORAN': 'Morán',
    'CM. ARAGUA DE BARCELONA': 'Aragua',
    'PQ. SAN PEDRO DEL RIO': 'San Pedro del Río',
    'PQ. SAN FRANCISCO DE ASIS': 'San Francisco de Asís',
    'PQ. LA MESA': 'La Mesa',
    'CM. ARAGUA': 'Piar',
    'CM. EL PALMAR': 'Padre Pedro Chien',
    'CM. MAPIRE': 'Monagas',
    'PQ. ALFREDO A LARRIVA': 'Alfredo Arvelo Larriva',
    'PQ. MANUEL MORILLO': 'Manuel Morillo',
    'PQ. EL CENIZO': 'El Cenizo',
    'CM. URACHICHE': 'Urachiche',
    'CM. OSPINO': 'Ospino',
    'PQ. SAN LUIS': 'San Luis',
    'PQ. SABANA LIBRE': 'Sabana Libre',
    'PQ. MARIARA': 'Mariara',
    'PQ. ELORZA': 'Elorza',
    'PQ. GUIGUE': 'Guigue',
    'PQ. SANTA FE': 'Santa Fe',
    'PQ. EL RECREO': 'El Recreo',
    'PQ. LA ESPERANZA': 'La Esperanza',
    'PQ. TORUNOS': 'Torunos',
    'PQ. LA PEÑA': 'La Peña',
    'PQ. MARIÑO': 'Mariño',
    'PQ. HUMOCARO BAJO': 'Humocaro Bajo',
    'PQ. PARHUEÑA': 'Parhueña',
    'PQ. EL TEJERO': 'El Tejero',
    'PQ.JOSE IGNACIO DEL PUMAR': 'José Ignacio del Pumar Pedraza',
    'PQ. VISTA AL SOL': 'Vista al Sol',
    'PQ. EL CARTANAL': 'El Cartanal',
    'PQ. EL VINCULO': 'El Vínculo',
    'PQ. FREITEZ': 'Freitez',
    'CM. SAN ANTONIO': 'Acosta',
    'PQ. CAMACARO': 'Camacaro',
    'PQ. MONS. MIGUEL A SALAS': 'Monseñor Miguel Antonio Salas',
    'PQ. ZARAZA': 'Zaraza',
    'PQ. SORO': 'Soro',
    'PQ. POTRERITOS': 'Potreritos',
    'PQ. GIBRALTAR': 'Gibraltar',
    'PQ. FRANCISCO EUGENIO B': 'Francisco Eugenio Bustamante',
    'PQ. PETARE': 'Petare',
    'CM. LA ASUNCION': 'Arismendi',
    'PQ. SANTA CATALINA': 'Santa Catalina',
    'PQ. URUMACO': 'Urumaco',
    'PQ. EL BATEY': 'El Batey',
    'PQ. APARICIO': 'Aparicio',
    'PQ. PAUJIL': 'El Paujil',
    'PQ. MARCELINO BRICEÑO': 'Marcelino Briceño',
    'PQ. CAMPO LARA': 'Campo Lara',
    'PQ. LA VEGA DE GUARAMACAL': 'Vega de Guaramacal',
    'PQ. HERIBERTO ARROYO': 'El Socorro',
    'PQ. CUA': 'Cúa',
    'PQ. ACHAGUAS': 'Achaguas',
    'PQ. LA SIERRITA': 'La Sierrita',
    'CM. SANTA ELENA DE UAIREN': 'Gran Sabana',
    'PQ. URB SAN DIEGO': 'San Diego',
    'PQ. ALBARICO': 'Albarico',
    'PQ. QUINIMARI': 'Quinimarí',
    'PQ. ANZOATEGUI': 'Anzoátegui',
    'PQ. GRAL FCO. A VASQUEZ': 'General Francisco Antonio Vásquez',
    'PQ. ANTONIO JOSE DE SUCRE': 'Antonio José de Sucre',
    'PQ. CUARA': 'Cuara',
    'PQ. LA GUANOTA': 'La Guanota',
    'PQ. U TOCUYITO': 'Tocuyito',
    'PQ. GUEVARA': 'Guevara',
    'PQ. VENANCIO PULGAR': 'Venancio Pulgar',
    'PQ. SANTA CLARA': 'Santa Clara',
    'PQ. LAS MERCEDES': 'Las Mercedes',
    'PQ. JUAN B RODRIGUEZ': 'Juan Bautista Rodríguez',
    'PQ. SAN RAFAEL DE A.': 'San Rafael de Alcázar',
    'PQ. COLINA': 'Colina',
    'CM. AROA': 'Bolívar',
    'CM. GUAMA': 'Sucre',
    'PQ. SANTOS DE ABELGAS': 'Santos de Abelgas',
    'PQ. SANTA MARIA DE IPIRE': 'Santa María de Ipire',
    'CM. PALMIRA': 'Guasimos',
    'PQ. SOUBLETTE': 'Soublette',
    'PQ. TAMACA': 'Tamaca',
    'PQ. TRES DE FEBRERO': 'Tres de Febrero',
    'CM. SAN JOSECITO': 'Torbes',
    'PQ. SANTA ROSALIA': 'Santa Rosalía',
    'PQ. RIO NEGRO': 'Río Negro',
    'PQ. PANAQUIRE': 'Panaquire',
    'PQ. TIARA': 'Tiara',
    'PQ. JUAN JOSE FLORES': 'Juan José Flores',
    'PQ. LASSO DE LA VEGA': 'Lasso de la Vega',
    'PQ. EL PROGRESO': 'El Progreso',
    'PQ. RIO ACARIGUA': 'Río Acarigua',
    'CM. STA. ANA  DEL TACHIRA': 'Córdoba',
    'PQ. EL SOCORRO': 'El Socorro',
    'PQ. TAVERA ACOSTA': 'Tavera Acosta',
    'PQ. GUAIBACOA': 'Guaibacoa',
    'PQ. EL MORRO': 'El Morro',
    'PQ. DIEGO DE LOZADA': 'Diego de Lozada',
    'PQ. CARRIZAL': 'Carrizal',
    'PQ. SANTA APOLONIA': 'Santa Apolonia',
    'PQ. ANDRES BELLO': 'Andrés Bello',
    'CM. LA GRITA': 'Jáuregui',
    'PQ. S ANTONIO DE YARE': 'San Antonio de Yare',
    'PQ. SAN VICENTE': 'San Vicente',
    'PQ. JOSE MARIA BLANCO': 'José María Blanco',
    'PQ. SAN FCO DE YARE': 'San Francisco de Yare',
    'PQ. SIMON BOLIVAR': 'Simón Bolívar',
    'PQ. PALACIOS FAJARDO': 'Palacios Fajardo',
    'CM. TUMEREMO': 'Sifontes',
    'PQ. PEDRO BRICEÑO MENDEZ': 'Pedro Briceño Méndez',
    'PQ. TUÑAME': 'Tuñame',
    'PQ. LA VICTORIA': 'La Victoria',
    'PQ. PAMPANITO II': 'Pampanito II',
    'PQ. OLEGARIO VILLALOBOS': 'Olegario Villalobos',
    'PQ. CUICAS': 'Cuicas',
    'PQ. JOSE RAMON YEPEZ': 'José Ramón Yepez',
    'PQ. ZUATA': 'Zuata',
    'PQ. CALDERAS': 'Calderas',
    'CM. DELICIAS': 'Delicias',
    'PQ. LAS VEGAS DEL TUY': 'Las Vegas del Tuy',
    'PQ. CABURE': 'Cabure',
    'PQ. JUNIN': 'Junín',
    'CM. BARRANCAS': 'Sotillo',
    'PQ. AGUAS CALIENTES': 'Aguas Calientes',
    'PQ. SAN JOSE DE GUARIBE': 'San José de Guaribe',
    'PQ. SANTA TERESA': 'Santa Teresa',
    'PQ. EL REGALO': 'El Regalo',
    'PQ. LA CEIBA': 'La Ceiba',
    'PQ. LA CANDELARIA': 'La Candelaria',
    'PQ. CACHIPO': 'Cachipo',
    'PQ. MUCUCHACHI': 'Mucuchachí',
    'CM. SAN ANT DEL GOLFO': 'Mejía',
    'PQ. JOSE VIDAL MARCANO': 'José Vidal Marcano',
    'PQ. CHACOPATA': 'Chacopata',
    'PQ. MANICUARE': 'Manicuare',
    'PQ. ARACUA': 'Aracua',
    'PQ. SN JUAN BAUTISTA': 'San Juan Bautista',
    'PQ. TOCUYO DE LA COSTA': 'Tocuyo de la Costa',
    'PQ. MAMPORAL': 'Mamporal',
    'PQ. ARENAS': 'Arenas',
    'PQ. SAN BERNARDINO': 'San Bernandino',
    'PQ. SAN ANDRES': 'San Andrés',
    'PQ. FARIA': 'Faria',
    'CM. TORONDOY': 'Justo Briceño',
    'PQ. CARAYACA': 'Carayaca',
    'PQ. EL PAUJI': 'El Paují',
    'PQ. JUAN A RODRIGUEZ D': 'Juan Antonio Rodríguez Domínguez',
    'PQ. TORRES': 'Torres',
    'CM. SOLEDAD': 'Independencia',
    'PQ. CAUCAGUA': 'Caucagua',
    'PQ. BARCELONETA': 'Barceloneta',
    'PQ. SAN JOSE DE AEROCUAR': 'San José de Aerocuar',
    'CM. PAMPATAR': 'Maneiro',
    'PQ. CHEREGUE': 'Cheregue',
    'PQ. JUANA DE AVILA': 'Juana de Ávila',
    'CM. CHABASQUEN': 'Monseñor José Vicente de Unda',
    'PQ. BOROJO': 'Borojo',
    'PQ. BORBURATA': 'Borburata',
    'PQ. RIBAS': 'Ribas',
    'PQ. MARIZAPA': 'Marizapa',
    'PQ. BARINITAS': 'Barinitas',
    'PQ. PTE. ROMULO GALLEGOS': 'Presidente Rómulo Gallegos',
    'PQ. EL ROSARIO': 'El Rosario',
    'PQ. FRANCISCO OCHOA': 'Francisco Ochoa',
    'PQ. LA QUEBRADA': 'La Quebrada',
    'PQ. STA MARIA DEL HORCON': 'Santa María del Horcón',
    'PQ. BARINAS': 'Barinas',
    'PQ. SAN JAVIER': 'San Javier',
    'PQ. EL CEDRO': 'Los Cedros',
    'PQ. NUEVA CUA': 'Nueva Cúa',
    'PQ. VALENTIN VALIENTE': 'Valentín Valiente',
    'PQ. SANTIAGO': 'Santiago',
    'PQ. AGUA VIVA': 'Agua Viva',
    'PQ. MANUEL SALVADOR ULLOA': 'Manuel Salvador Ulloa',
    'PQ. SAN SILVESTRE': 'San Silvestre',
    'PQ. PECAYA': 'Pecaya',
    'PQ. CHORONI': 'Choroní',
    'PQ. MOITACO': 'Moitaco',
    'PQ. DOLORES': 'Dolores',
    'PQ. EL RINCON': 'El Rincón',
    'CM. PALO NEGRO': 'Libertador',
    'PQ. JOSE FELIX RIBAS': 'José Félix Ribas',
    'CM. EL LIMON': 'Mario Briceño Iragorry',
    'CM. TEMBLADOR': 'Libertador',
    'PQ. PAYARA': 'Payara',
    'PQ. TUNAPUY': 'Tunapuy',
    'PQ. MACARAPANA': 'Macarapana',
    'PQ. CACIQUE MARA': 'Cacique Mara',
    'CM. CAMATAGUA': 'Camatagua',
    'PQ. PUEBLO NUEVO': 'Pueblo Nuevo',
    'PQ. MANUEL DAGNINO': 'Manuel Dagnino',
    'PQ. JUAN DE MATA SUAREZ': 'Juan de Mata Suárez',
    'PQ. LARA': 'Lara',
    'PQ. EL CARMEN': 'El Carmen',
    'PQ. S LORENZO DE TIZNADOS': 'San Lorenzo de Tiznados',
    'PQ. SAN JUAN': 'San Juan',
    'PQ. CIUDAD ALIANZA': 'Ciudad Alianza',
    'CM. UPATA': 'Piar',
    'PQ. EL PINTO': 'El Pinto',
    'CM. CORDERO': 'Andrés Bello',
    'PQ. ESTANQUES': 'Estanquez',
    'PQ. PEÑA BLANCA': 'Peña Blanca',
    'CM. SAN FELIPE': 'San Felipe',
    'PQ.SAN JUAN DE LOS MORROS': 'San Juan de los Morros',
    'PQ. CHACANTA': 'Chacanta',
    'PQ. PANAPANA': 'Panapana',
    'PQ. SANTA MARIA': 'Santa María',
    'PQ. MACUTO': 'Macuto',
    'CM. EL COBRE': 'Vargas',
    'PQ. LOS CORTIJOS': 'Los Cortijos',
    'PQ. SAN FRANCISCO': 'San Francisco',
    'PQ. TAGUAYA': 'Taguaya',
    'PQ. PIAR': 'Piar',
    'PQ. ANTONIO BORJAS ROMERO': 'Antonio Borjas Romero',
    'PQ. HERAS': 'Heras',
    'PQ. SIXTO ZAMBRANO': 'Sixto Zambrano',
    'PQ. LUIS ALBERTO GOMEZ': 'Luis Alberto Gómez',
    'CM. SAN JOSE DE GUANIPA': 'San José de Guanipa',
    'PQ. CAMPO ALEGRE': 'Campo Alegre',
    'PQ.SAN JOSE DE LA MONTAÑA': 'San José de la Montaña',
    'PQ. CUPIRA': 'Cupira',
    'PQ. EL BAJO': 'El Bajo',
    'PQ. LA PUEBLITA': 'La Pueblita',
    'PQ. CARRILLO': 'Carrillo',
    'CM. ABEJALES': 'Libertador',
    'PQ. VALMORE RODRIGUEZ': 'Valmore Rodríguez',
    'PQ. LA TRINIDAD': 'La Trinidad',
    'PQ. PEDRO COVA': 'Pedro Cova',
    'PQ. RAMON IGNACIO MENDEZ': 'Ramón Ignacio Méndez',
    'CM. MARIPA': 'Sucre',
    'CM.LA PLAZA DE PARAGUACHI': 'Antolín del Campo',
    'CM. SAN SIMON': 'Simón Rodríguez',
    'PQ. JAJI': 'Jají',
    'PQ. AMBROSIO': 'Ambrosio',
    'PQ. JUAN VICENTE GOMEZ': 'Juan Vicente Gómez',
    'PQ. SINAMAICA': 'Sinamaica',
    'PQ. LOS BARALES': 'Los Barales',
    'CM. SANTO DOMINGO': 'Cardenal Quintero',
    'PQ. LA UNION': 'La Unión',
    'PQ. JACINTO PLAZA': 'Jacinto Plaza',
    'PQ. SEQUE': 'Seque',
    'PQ. LA CIENAGA': 'La Ciénaga',
    'PQ. RICAURTE': 'Ricaurte',
    'PQ.SAN JUAN GUANAGUANARE': 'San Juan de Guanaguanare',
    'PQ. EL CARMELO': 'El Carmelo',
    'PQ. PUERTO VIVAS': 'Puerto Vivas',
    'PQ. MENDOZA': 'Mendoza',
    'PQ. ALTOS DE LOS GODOS': 'Alto de Los Godos',
    'PQ. CARIRUBANA': 'Carirubana',
    'PQ. SAN GABRIEL': 'San Gabriel',
    'PQ. CARIACO': 'Cariaco',
    'PQ. SAN CARLOS DE AUSTRIA': 'San Carlos de Austria',
    'PQ. ARIPAO': 'Aripao',
    'PQ. AREVALO APONTE': 'Arévalo Aponte',
    'PQ. SAN CRISTOBAL': 'San Cristóbal',
    'PQ. CABRUTA': 'Cabruta',
    'PQ. CARMEN HERRERA': 'Carmen Herrera',
    'PQ. MANTECAL': 'Mantecal',
    'PQ. BELEN': 'Belén',
    'PQ. CARUAO': 'Caruao',
    'PQ. QUINTERO': 'Quintero',
    'PQ. CHARALLAVE': 'Charallave',
    'PQ. EL HATO': 'El Hato',
    'PQ. DOMINGA ORTIZ P': 'Dominga Ortiz de Páez',
    'PQ. BELLA VISTA': 'Bella Vista',
    'PQ. MUCUTUY': 'Mucutuy',
    'PQ. PUEBLO CUMAREBO': 'Pueblo Cumarebo',
    'PQ. ALTAMIRA': 'Altamira',
    'PQ. SN RAFAEL DE ATAMAICA': 'San Rafael de Atamaica',
    'PQ. GERMAN RIOS LINARES': 'Germán Ríos Linares',
    'PQ. CAÑO DELGADITO': 'Caño Delgadito',
    'PQ. BOLIVIA': 'Bolivia',
    'PQ. GABRIEL PICON G.': 'Gabriel Picón González',
    'PQ. LA ESTACION': 'La Estación',
    'PQ. LAS PARCELAS': 'Las Parcelas',
    'PQ. EL MOLINO': 'El Molino',
    'CM. LA AZULITA': 'Andrés Bello',
    'CM. PUERTO LA CRUZ': 'Puerto la Cruz',
    'PQ. UNION': 'Unión',
    'PQ. ANTOLIN TOVAR AQUINO': 'Antolín Tovar Aquino',
    'PQ. SAN JUAN DE LOS CAYOS': 'San Juan de los Cayos',
    'PQ. MILLA': 'Milla',
    'PQ. UVERITO': 'Uverito',
    'CM. GUANARE': 'Guanare',
    'PQ. CHEJENDE': 'Chejendé',
    'PQ. SAN ISIDRO': 'San Isidro',
    'CM. SAN SEBASTIAN': 'San Sebastián',
    'PQ. IDELFONZO VASQUEZ': 'Idelfonso Vásquez',
    'PQ. SAN FELIX': 'San Félix',
    'PQ. SAN TIMOTEO': 'San Timoteo',
    'CM. PALMASOLA': 'Palmasola',
    'PQ. LEZAMA': 'Lezama',
    'PQ. LA VELA DE CORO': 'La Vela de Coro',
    'CM. COLONCITO': 'Panamericano',
    'PQ. CRUZ CARRILLO': 'Cruz Carrillo',
    'PQ. SAN RAFAEL': 'San Rafael'
}


if __name__ == '__main__':
    CSV_states={'EDO. LA GUAIRA', 'EDO. CARABOBO', 'EDO. FALCON', 'EDO. TACHIRA', 'EDO. COJEDES', 'EDO. APURE', 'EDO. SUCRE', 'EDO. GUARICO', 'EDO. DELTA AMAC', 'EDO. MERIDA', 'EDO. ANZOATEGUI', 'EDO. PORTUGUESA', 'EDO. LARA', 'EDO. TRUJILLO', 'EDO. ZULIA', 'EDO. MIRANDA', 'EDO. BARINAS', 'DTTO. CAPITAL', 'EDO. YARACUY', 'EDO. MONAGAS', 'EDO.NVA.ESPARTA', 'EDO. ARAGUA', 'EDO. BOLIVAR', 'EDO. AMAZONAS'}
    CSV_munips={'MP. MICHELENA', 'MP. PIAR', 'MP. SANTOS MARQUINA', 'MP. AGUASAY', 'MP. URUMACO', 'MP. J.V. CAMPO ELIAS', 'MP. TOVAR', 'MP. CARLOS ARVELO', 'MP. MONTE CARMELO', 'MP. LOS TAQUES', 'MP. CAMAGUAN', 'MP. OSPINO', 'MP. SAN DIEGO', 'MP. SOSA', 'MP.ROSARIO DE PERIJA', 'MP. LOS SALIAS', 'MP. ANZOATEGUI', 'MP. MANEIRO', 'MP. ANACO', 'MP. MARACAIBO', 'MP. MONAGAS', 'MP. ARISMENDI', 'MP. ZARAZA', 'MP. ACHAGUAS', 'MP. EL HATILLO', 'MP. GUACARA', 'MP. MOTATAN', 'MP. ARISTIDES BASTID', 'MP. SEBORUCO', 'MP. MACHIQUES DE P', 'MP.S JUAN CAPISTRANO', 'MP. PEÑA', 'MP. PEDRO GUAL', 'MP. FERNANDEZ FEO', 'MP. JOSE R REVENGA', 'MP. CAPACHO VIEJO', 'MP.OCUMARE D L COSTA', 'MP. SAN FERNANDO', 'MP. IRIBARREN', 'MP. MEJIA', 'MP. ARICAGUA', 'MP. MATURIN', 'MP. ARAURE', 'MP. PEDERNALES', 'MP. SANTIAGO MARIÑO', 'MP. JESUS M SEMPRUN', 'MP. MC GREGOR', 'MP. TINACO', 'MP. LIBERTAD', 'MP. ARAGUA', 'MP. PUNCERES', 'MP. URACHICHE', 'MP. BEJUMA', 'MP. EZEQUIEL ZAMORA', 'MP. LA CAÑADA DE U.', 'MP. TUREN', 'MP. CACIQUE MANAURE', 'MP. RAFAEL URDANETA', 'MP. SAN JOAQUIN', 'MP. S MARIA DE IPIRE', 'MP. ARZOBISPO CHACON', 'MP. RANGEL', 'MP. COCOROTE', 'MP. JOSE ANGEL LAMAS', 'MP. SIMON BOLIVAR', 'MP. ROJAS', 'MP. A JOSE DE SUCRE', 'MP. JOSE FELIX RIBAS', 'MP. BOCONO', 'MP. ANTONIO ROMULO C', 'MP. DABAJURO', 'MP. CARIRUBANA', 'MP. MARIÑO', 'MP.CARDENAL QUINTERO', 'MP. FALCON', 'MP. JOSE M. VARGAS', 'MP.VALMORE RODRIGUEZ', 'MP. CARACCIOLO PARRA', 'MP. CARIPE', 'MP. RICAURTE', 'MP. JUAN JOSE MORA', 'MP. SAMUEL MALDONADO', 'MP.PADRE PEDRO CHIEN', 'MP. ZEA', 'MP.FRANCISCO LINARES', 'MP. SUCRE', 'MP. ESTELLER', 'MP. ESCUQUE', 'MP. MELLADO', 'MP. MONTALBAN', 'MP. FRANCISCO J PULG', 'MP. SILVA', 'MP. MUÑOZ', 'MP. ANDRES BELLO', 'MP. ACEVEDO', 'MP. L/DIEGO BAUTISTA', 'MP. SAN CRISTOBAL', 'MP. INDEPENDENCIA', 'MP. JIMENEZ', 'MP.JULIO CESAR SALAS', 'MP.S JOSE DE GUARIBE', 'MP. SAN FRANCISCO', 'MP. PLAZA', 'MP. BARALT', 'MP. GUASIMOS', 'MP. MONTES', 'MP. COLON', 'MP. SANTA ANA', 'MP. RAFAEL RANGEL', 'MP. COLINA', 'MP. VEROES', 'MP. AUTONOMO TINAQUI', 'MP. BLVNO LIBERTADOR', 'MP. NIRGUA', 'MP. BIRUACA', 'MP. MONS. ITURRIZA', 'MP. INFANTE', 'MP. PAZ CASTILLO', 'MP. CHACAO', 'MP. CAJIGAL', 'MP. URACOA', 'MP. BARUTA', 'MP. PEÑALVER', 'MP. TRUJILLO', 'MP. ANTONIO PINTO S.', 'MP. VALENCIA', 'MP. GUANTA', 'MP. PAEZ', 'MP. CORDOBA', 'MP. SIFONTES', 'MP. OBISPOS', 'MP. TULIO F CORDERO', 'MP. SANTOS MICHELENA', 'MP. RIBAS', 'MP. UNION', 'MP. CRESPO', 'MP. LOBATERA', 'MP.GENARO BOCONOITO', 'MP. MARA', 'MP. CEDEÑO', 'MP. ROMULO GALLEGOS', 'MP.OB. RAMOS DE LORA', 'MP. PETIT', 'MP. CARRIZAL', 'MP. PAPELON', 'MP. CARACHE', 'MP. BARINAS', 'MP. PEDRAZA', 'MP. FREITES', 'MP. GUANIPA', 'MP.VILLALBA(I.COCHE)', 'MP. M.JOSE V DE UNDA', 'MP. MARIO B IRAGORRY', 'MP. VARGAS', 'MP. MAUROA', 'MP. LIMA BLANCO', 'MP. CRUZ PAREDES', 'MP. SANTA BARBARA', 'MP. PAMPAN', 'MP. PUERTO CABELLO', 'MP. GUANARITO', 'MP. CAMATAGUA', 'MP. PUEBLO LLANO', 'MP. EL SOCORRO', 'MP. VALERA', 'MP. BENITEZ', 'MP. SANTA ROSALIA', 'MP. BRION', 'MP. ACOSTA', 'MP. GRAN SABANA', 'MP. PALAVECINO', 'MP. GUANARE', 'MP.JOSE ANTONIO PAEZ', 'MP. MANUEL MONGE', 'MP. ALBERTO ARVELO T', 'MP. LOS GUAYOS', 'MP. LANDER', 'MP. SANTA RITA', 'MP. TOCOPERO', 'MP.S RAFAEL DE ONOTO', 'MP. EL CALLAO', 'MP. TUCUPITA', 'MP. GARCIA DE HEVIA', 'MP. CABIMAS', 'MP. ANDRES MATA', 'MP. MIRANDA', 'MP. VALDEZ', 'MP. SAN JUDAS TADEO', 'MP. PAMPANITO', 'MP. CAMPO ELIAS', 'MP. LA CEIBA', 'MP. JACURA', 'MP. BLVNO DE ANGOSTU', 'MP. RIBERO', 'MP. GIRARDOT', 'MP. PEDRO CAMEJO', 'MP. CAPACHO NUEVO', 'MP. ALBERTO ADRIANI', 'MP. J.F.MARQUEZ C.', 'MP.PEDRO MARIA UREÑA', 'MP. JUSTO BRICEÑO', 'MP. PALMASOLA', 'MP. TORBES', 'MP. ANGOSTURA DEL OR', 'MP. BRUZUAL', 'MP. CANDELARIA', 'MP. AGUA BLANCA', 'MP. PAO S J BAUTISTA', 'MP. BERMUDEZ', 'MP. ZAMORA', 'MP. LAGUNILLAS', 'MP. JESUS E LOSSADA', 'MP. CRUZ S ACOSTA', 'MP. BUROZ', 'MP. PIRITU', 'MP. ROSCIO', 'MP. CARONI', 'MP. GARCIA', 'MP.ANTOLIN DEL CAMPO', 'MP. PANAMERICANO', 'MP. SAN FELIPE', 'MP. URDANETA', 'MP. DIEGO IBARRA', 'MP. SAN CASIMIRO', 'MP. BUCHIVACOA', 'MP. CARVAJAL', 'MP. JUAN JOSE RONDON', 'MP. LA TRINIDAD', 'MP. DIAZ', 'MP. ATURES', 'MP. AYACUCHO', 'MP.SAN GERONIMO DE G', 'MP. TORRES', 'MP.PENIN. DE MACANAO', 'MP. MARCANO', 'MP. CARDENAS', 'MP. CASACOIMA', 'MP. GOMEZ', 'MP. CATATUMBO', 'MP. ORTIZ', 'MP. ANDRES E. BLANCO', 'MP. ANDRES E BLANCO', 'MP. JUNIN', 'MP. FCO DE MIRANDA', 'MP. LIBERTADOR', 'MP. MORAN', 'MP. INDIGENA BLVNO G', 'MP. ANTONIO DIAZ', 'MP. PADRE NOGUERA', 'MP. FEDERACION', 'MP. RIVAS DAVILA', 'MP. SAN SEBASTIAN', 'MP. URIBANTE', 'MP. SOTILLO', 'MP.S RAFAEL CARVAJAL', 'MP. SIMON RODRIGUEZ', 'MP. NAGUANAGUA', 'MP. JUAN GERMAN ROSC', 'MP. CHAGUARAMAS', 'MP. JAUREGUI', 'MP. BOLIVAR', 'MP. TUBORES', 'MP. GUARAQUE', 'MP. CRISTOBAL ROJAS', 'MP. GUAICAIPURO'}
    CSV_parroquias={'CM. MARIGUITAR', 'PQ. DIVINA PASTORA', 'PQ. ADICORA', 'CM. BOCONOITO', 'PQ. CAPADARE', 'PQ. GUARAMACAL', 'PQ. ENCONTRADOS', 'PQ. MONTES DE OCA', 'PQ. GUAJIRO', 'PQ. CORDOBA', 'CM. NUEVA BOLIVIA', 'PQ.TRINIDAD DE LA CAPILLA', 'PQ. AGUIRRE', 'PQ. FLOR DE PATRIA', 'PQ. CHURUGUARA', 'PQ. LA CONCORDIA', 'PQ. PIO TAMAYO', 'PQ. PIRITU', 'PQ. PUNTA DE PIEDRAS', 'PQ. SAN MARTIN DE PORRES', 'C.M. MATURIN', 'PQ. SABANA GRANDE', 'PQ. LOS CAPRICHOS', 'PQ. MOSQUEY', 'PQ. CANDELARIA', 'PQ. CHIQUINQUIRA', 'PQ. ALTAGRACIA DE ORITUCO', 'PQ. ALTAGRACIA DE LA M', 'PQ. EL PAO', 'PQ. MAPARARI', 'PQ. CARLOS SOUBLETTE', 'CM. EL PLAYON', 'PQ. PAMPAN', 'PQ. CANTAGALLO', 'PQ. BARTOLOME SALOM', 'PQ. TICOPORO', 'PQ. TAMARE', 'PQ. JACURA', 'PQ. MUCURUBA', 'PQ. FLORIDA', 'PQ. PULIDO MENDEZ', 'PQ. URAMA', 'CM. BAILADORES', 'PQ. LA PASTORA', 'PQ. NAIGUATA', 'PQ. SAN RAFAEL DE ORITUCO', 'PQ. MIRANDA', 'CM. SANTA ANA', 'PQ. CECILIO ACOSTA', 'PQ. AREVALO GONZALEZ', 'PQ. MORUY', 'CM. TARIBA', 'PQ. BOCA DE UCHIRE', 'PQ. JALISCO', 'PQ. RIO CHICO', 'CM. JUAN VICENTE BOLIVAR', 'PQ. 23 DE ENERO', 'CM. GUASIPATI', 'CM.SAN RAFAEL DEL PIÑAL', 'PQ. CONSTITUCION', 'PQ. EL CHAPARRO', 'PQ. PQ AUGUSTO MIJARES', 'PQ. LA ROSA', 'PQ. M.ARTURO CELESTINO A', 'PQ. EL RASTRO', 'PQ. BIDEAU', 'PQ. QUESERAS DEL MEDIO', 'PQ. BIRUACA', 'PQ. LA PALMITA', 'PQ. SAN CAMILO', 'PQ. AGUA SANTA', 'PQ. LECHERIAS', 'PQ.SAN JOSE DE BARLOVENTO', 'PQ. BOCA DE AROA', 'PQ. EL CAFE', 'PQ. LIBERTAD', 'PQ. LA PICA', 'PQ.GRAN MARISCAL', 'PQ. CABIMBU', 'PQ. JUAN GERMAN ROSCIO', 'PQ. SAN ANTONIO DE IRAPA', 'PQ. EL AMPARO', 'PQ. NUEVA ARCADIA', 'PQ. JUAREZ', 'PQ. MARIANO PARRA LEON', 'PQ. FILAS DE MARICHE', 'CM. TIMOTES', 'PQ. ANA MARIA CAMPOS', 'PQ. ARAGUITA', 'PQ. LA PAZ', 'PQ. ANACO', 'PQ. SAN JOAQUIN', 'PQ. SABANA DE PIEDRA', 'PQ. MONTALBAN', 'PQ. ARAYA', 'PQ. MONSEÑOR JAUREGUI', 'PQ. ZAZARIDA', 'PQ. VALERITA', 'PQ. SIQUISIQUE', 'PQ. BRAMON', 'PQ. GUIRIA', 'PQ. ALMIRANTE LUIS BRION', 'CM. CARIPE', 'PQ. CURIEPE', 'PQ. TINTORERO', 'PQ. SAN LORENZO', 'PQ. DALLA COSTA', 'PQ. UVENCIO A VELASQUEZ', 'PQ. LA AGUADITA', 'PQ.CARACCIOLO PARRA PEREZ', 'PQ. CURIMAGUA', 'CM. NIRGUA', 'PQ. BOCA DE GRITA', 'PQ. CASTAÑEDA', 'PQ. NORTE', 'PQ. CAPAYA', 'CM. YARITAGUA', 'PQ. UDON PEREZ', 'PQ. U LOS GUAYOS', 'PQ. OCUMARE DE LA COSTA', 'PQ. GUARDATINAJAS', 'PQ. JUSEPIN', 'CM. SAN JOSE DE BOLIVAR', 'PQ. EMILIO C. GUERRERO', 'PQ. JOSE BERNARDO DORANTE', 'PQ. IGNACIO BRICEÑO', 'PQ. CHAGUARAMAS', 'PQ. MESA DE LAS PALMAS', 'PQ. CARABALLEDA', 'PQ. LA BEATRIZ', 'PQ. FRANCISCO FAJARDO', 'PQ. ARNOLDO GABALDON', 'CM. RUBIO', 'PQ. VALLE DE LA PASCUA', 'PQ. SANTA CRUZ DE GUACAS', 'PQ. LA TOMA', 'PQ. GUZMAN GUILLERMO', 'PQ. POZUELOS', 'PQ. VIENTO FRESCO', 'CM. SAN PABLO', 'PQ. CORAZON DE JESUS', 'CM. TOCOPERO', 'PQ. SN DIEGO DE CABRUTICA', 'CM. CIUDAD PIAR', 'PQ. JUAN IGNACIO MONTILLA', 'PQ. GUAIMARAL', 'CM. ARICAGUA', 'PQ. EL GUAYABO', 'PQ. MAIQUETIA', 'CM. LOBATERA', 'PQ. PLATANILLAL', 'CM. CAICARA', 'PQ. JOSE ANTONIO PAEZ', 'PQ. LEONCIO MARTINEZ', 'PQ. YOCOIMA', 'PQ. PIMPINELA', 'PQ. ADRIAN', 'PQ. PEDRO MARIA MORANTES', 'PQ. RAFAEL RANGEL', 'PQ. RINCON HONDO', 'PQ. STA.CRUZ DE BUCARAL', 'PQ. MONS. ARGIMIRO GARCIA', 'PQ. SALOM', 'PQ. CARDENAS', 'CM. SEBORUCO', 'PQ. HILARIO LUNA Y LUNA', 'PQ. MUCURITAS', 'PQ. PUNTA CARDON', 'PQ. CEGARRA', 'PQ. FRANCISCO DE MIRANDA', 'CM. MUCUCHIES', 'CM. QUENIQUEA', 'PQ. ELOY PAREDES', 'PQ. ANDRES ELOY BLANCO', 'PQ. CALABOZO', 'PQ. EL MORRO DE PTO SANTO', 'PQ. IMATACA', 'PQ. JOSE CASANOVA GODOY', 'PQ. INDEPENDENCIA', 'PQ. REYES VARGAS', 'PQ. DOMITILA FLORES', 'PQ. PRESIDENTE PAEZ', 'PQ. LEONARDO RUIZ PINEDA', 'PQ. EL CANTON', 'PQ. EL SOMBRERO', 'PQ. SANTO DOMINGO', 'CM. EL CALLAO', 'PQ. COCOLLAR', 'PQ. MATASIETE', 'PQ. OCUMARE DEL TUY', 'PQ. MORALITO', 'PQ. CATUARO', 'CM. PIRITU', 'PQ. OBISPOS', 'PQ. OSUNA RODRIGUEZ', 'PQ. GUERRERA ANA SOTO', 'CM. GUARAQUE', 'PQ. ALTAGRACIA', 'CM. SAN CASIMIRO', 'CM. VALLE ESP SANTO', 'PQ. ARISMENDI', 'PQ. MACARAO', 'PQ. SAN BLAS', 'PQ. MONSEÑOR CARRILLO', 'PQ. AGUA LINDA', 'PQ. PEDRO JOSE OVALLES', 'CM. SAN JUAN BAUTISTA', 'PQ. SAN PABLO', 'PQ. YAGUARAPARO', 'PQ. LAS MINAS DE BARUTA', 'PQ. PIÑANGO', 'PQ. LA VEGA', 'PQ. TUCACAS', 'PQ. COQUIVACOA', 'PQ. COJEDES', 'PQ. MACHURUCUTO', 'PQ. CIUDAD DE NUTRIAS', 'PQ. EL JARILLO', 'PQ. LOS TEQUES', 'PQ. SAN FRANCISCO DE CARA', 'CM. CAPACHO NUEVO', 'CM. ONOTO', 'PQ. SAN JOSE DE UNARE', 'PQ. VIRGEN DEL VALLE', 'PQ. CAÑO EL TIGRE', 'PQ. ROMAN CARDENAS', 'PQ. BOBURES', 'CM. SANTA BARBARA', 'CM. LAS MESAS', 'PQ. NAGUANAGUA', 'PQ. JOAQUIN CRESPO', 'PQ. LA PETROLEA', 'PQ. CARACHE', 'PQ. SAN AGUSTIN', 'PQ. ADAURE', 'PQ. MAGDALENO', 'PQ. CATEDRAL', 'PQ. CUMANACOA', 'PQ. CAMPO CLARO', 'CM. SAN MATEO', 'PQ. RIVAS BERTI', 'PQ. PARACOTOS', 'PQ. YACAMBU', 'CM. TABAY', 'PQ. BARUTA', 'PQ. CHIRICA', 'PQ. BURBUSAY', 'PQ. VICENTE FUENTES', 'PQ. MACAPO', 'PQ. CIPRIANO CASTRO', 'PQ. PUERTO SANTO', 'CM. URACOA', 'PQ. SAN JUAN DE PAYARA', 'CM. ACARIGUA', 'PQ. JADACAQUIVA', 'PQ. SANTA RITA', 'PQ. LUIS B. PRIETO F.', 'PQ. GUACHARA', 'CM. ARAPUEY', 'PQ. GUATIRE', 'CM. YUMARE', 'PQ. RENDON', 'CM. LA TENDIDA', 'PQ. VENEZUELA', 'PQ. SANTA CRUZ DEL ZULIA', 'PQ. URDANETA', 'CM. BARBACOAS', 'PQ. EL YAGUAL', 'PQ. EL HATILLO', 'PQ. CARLOS QUEVEDO', 'PQ. SABANETA', 'PQ. LOS GUASIMITOS', 'PQ. ARIAS', 'PQ. TRES ESQUINAS', 'PQ. LAS COCUIZAS', 'PQ. MERCEDES DIAZ', 'PQ. CURIAPO', 'PQ. ALTO BARINAS', 'PQ. SAN JOSE DE TIZNADOS', 'PQ. PALMIRA', 'PQ. TACARIGUA', 'CM. STA ELENA DE ARENALES', 'PQ. SAN FERNANDO', 'PQ. MADRE MA DE SAN JOSE', 'CM. CHIVACOA', 'PQ. GONZALO PICON FEBRES', 'PQ. GUASDUALITO', 'PQ. LA VENTA', 'PQ. JUAN RODRIGUEZ SUAREZ', 'PQ. MANUEL PIAR', 'CM. PUNTA DE PIEDRAS', 'PQ. BOCA DE CHAVEZ', 'PQ. PRESIDENTE BETANCOURT', 'PQ. ONCE DE ABRIL', 'PQ. ESPINO', 'PQ. SAN JOAQUIN DE NAVAY', 'PQ. CASIGUA', 'PQ. ALFREDO PACHECO M', 'PQ. VIRGEN DE LA COROMOTO', 'CM. UREÑA', 'PQ. FERNANDO GIRON TOVAR', 'CM. AGUA BLANCA', 'PQ. JUAN ANGEL BRAVO', 'PQ. ESPINOZA LOS MONTEROS', 'PQ. HECTOR AMABLE MORA', 'PQ. FRATERNIDAD', 'CM. PREGONERO', 'PQ. SAN SIMON', 'PQ. LAS ALHUACAS', 'PQ. JUAN BAUTISTA ARISMEN', 'PQ. MANUEL GUANIPA MATOS', 'PQ. QBDA. HONDA DE GUACHE', 'CM. PUNTA DE MATA', 'PQ. JAJO', 'CM. PAPELON', 'PQ. SUCRE', 'CM. FARRIAR', 'PQ. GUANTA', 'PQ. AGUSTIN CODAZZI', 'PQ. CANELONES', 'CM. EL CONSEJO', 'PQ. LAS PIEDRAS', 'PQ. MONTE CARMELO', 'PQ. SAN CARLOS DEL ZULIA', 'PQ. POTOSI', 'PQ. XAGUAS', 'PQ. CRNEL. MARIANO PERAZA', 'PQ. MATRIZ', 'PQ. LAS DELICIAS', 'PQ. SANTA ISABEL', 'PQ. GENERAL URDANETA', 'PQ. ANTONIO N BRICEÑO', 'PQ. EL BLANCO', 'PQ. CARACCIOLO PARRA P', 'PQ. BARIRO', 'PQ. SAN SEBASTIAN', 'CM. ZEA', 'CM. UMUQUENA', 'CM. STA CRUZ DE MORA', 'PQ. SAN BENITO', 'PQ. HERNANDEZ', 'PQ. DR. FCO. ROMERO LOBO', 'CM. MICHELENA', 'PQ. CHICHIRIVICHE', 'CM. CLARINES', 'PQ. CAÑA DE AZUCAR', 'PQ. LOS TACARIGUAS', 'CM. VILLA DE CURA', 'PQ. BOCA DE TOCUYO', 'CM. SANTA CRUZ', 'PQ. ORTIZ', 'PQ. SAN JOSE DE SAGUAZ', 'PQ. SANTA CRUZ', 'PQ. EL CUJI', 'PQ. PANAMERICANA', 'PQ. EL PILAR', 'PQ. CABUDARE', 'PQ. GOAIGOAZA', 'PQ. TUCUPIDO', 'PQ. EL LLANO', 'PQ. SAN JUAN DE LAS GALDO', 'PQ. PAPARO', 'PQ. PUEBLO NUEVO DEL SUR', 'PQ. AYACUCHO', 'PQ. EL JUNQUITO', 'PQ. BRUZUAL', 'PQ. SABANA DE MENDOZA', 'PQ. SANTA BARBARA', 'PQ. CAMAGUAN', 'PQ. PALOTAL', 'PQ. APURITO', 'PQ. CONCEPCION', 'PQ. ARAURIMA', 'CM. MIRIMIRE', 'PQ. PARAPARA', 'PQ. AGUA CALIENTE', 'PQ. ESCUQUE', 'PQ. ANDRES LINARES', 'CM. LA FRIA', 'PQ. GUAYABAL', 'PQ. MONTA¿A VERDE', 'CM. CANAGUA', 'PQ. RAMON PERAZA', 'PQ. MARCIAL HERNANDEZ', 'PQ. PEDERNALES', 'PQ. FRANCISCO J PULGAR', 'PQ. ANTONIO SPINETTI DINI', 'CM. JUAN GRIEGO', 'PQ.TACARIGUA DE LA LAGUNA', 'PQ. SAN ANTONIO', 'PQ. EL JAGUITO', 'PQ. SAN FCO DE MACAIRA', 'PQ. RAUL CUENCA', 'PQ. RODRIGUEZ DOMINGUEZ', 'PQ. GUADARRAMA', 'PQ. EL DIVIDIVE', 'PQ. GUARENAS', 'PQ. MARHUANTA', 'PQ. JOSE CENOVIO URRIBARR', 'PQ. PAEZ', 'PQ. CASTOR NIEVES RIOS', 'PQ. SAN MIGUEL', 'PQ. BARAIVED', 'CM. TURMERO', 'PQ. LAS PEÑITAS', 'PQ. STA RITA DE MANAPIRE', 'PQ. JOSE G HERNANDEZ', 'PQ. JOSE DOMINGO RUS', 'PQ. LIBERTADOR', 'PQ. PUERTO DE NUTRIAS', 'PQ. JUDIBANA', 'PQ. ARAMENDI', 'CM. CARIPITO', 'PQ. ALBERTO ADRIANI', 'PQ. CODAZZI', 'PQ. BERGANTIN', 'PQ. LA SABANITA', 'PQ. ACEQUIAS', 'PQ. PAO DE ZARATE', 'PQ. JESUS M SEMPRUN', 'PQ. LAS MAJADAS', 'PQ. LA APARICION', 'PQ. PAMPANITO', 'PQ. SAN JOSE DE LA COSTA', 'CM. SAN PEDRO DE COCHE', 'PQ. EL VALLE', 'PQ. LA CONCEPCION', 'PQ. EMETERIO OCHOA', 'PQ. BOCA DEL PAO', 'PQ. TACATA', 'PQ. CAPATARIDA', 'PQ. CRISTOBAL COLON', 'PQ. AMENODORO RANGEL LAMU', 'PQ. EL COROZO', 'CM. LAS TEJERIAS', 'PQ. SAN RAFAEL DE LAYA', 'PQ. VALLE MORIN', 'PQ. LA URBANA', 'PQ. LA DEMOCRACIA', 'PQ. TUNAPUICITO', 'PQ. EL MENE', 'PQ. BOCONO', 'PQ. CRISTOBAL MENDOZA', 'PQ. ZEA', 'PQ. CACHAMAY', 'PQ. HIGUEROTE', 'PQ. 5 DE JULIO', 'PQ. ORINOCO', 'PQ. RAMON I MENDEZ', 'PQ. MOROTURO', 'CM. PUEBLO LLANO', 'PQ. ROMULO BETANCOURT', 'PQ. LA DOLORITA', 'CM. AGUASAY', 'PQ. PARAUTE', 'PQ. JOSE NUCETE SARDI', 'PQ. HUMOCARO ALTO', 'PQ. TRINIDAD SAMUEL', 'PQ. CAMPO ELIAS', 'PQ. CARMEN DE CURA', 'PQ. SANTA ROSA', 'PQ. SAGRARIO', 'PQ. ALTA GUAJIRA', 'PQ. CAPURI', 'CM. STA MARIA DE CAPARO', 'CM. CAICARA DEL ORINOCO', 'PQ. SANTA LUCIA', 'CM. COLONIA TOVAR', 'PQ. AGUA SALADA', 'PQ. ARICAGUA', 'CM. DABAJURO', 'PQ. BOLIVAR', 'CM. YARACAL', 'CM. LAGUNILLAS', 'PQ. CARVAJAL', 'PQ. LA SOLEDAD', 'PQ. MENE DE MAUROA', 'PQ. MAMO', 'CM. SANTA RITA', 'PQ. EL CAFETAL', 'PQ. CHIGUARA', 'PQ. TOVAR', 'PQ. SAMAN DE GUERE', 'PQ. BETIJOQUE', 'PQ.BARTOLOME DE LAS CASAS', 'PQ. SOSA', 'CM. TUCANI', 'PQ. MESA DE QUINTERO', 'PQ.SAN RAFAEL PALO ALZADO', 'PQ. SAN CRISTOBAL DE T', 'PQ. GRANADOS', 'PQ. CHORRERON', 'PQ. CIUDAD BOLIVIA', 'PQ. PADRE BARRAL', 'CM. PORLAMAR', 'PQ. BARRANCAS', 'PQ. TEMERLA', 'PQ. CACUTE', 'PQ. CAIGUA', 'PQ. EL BAÑO', 'PQ. EL REAL', 'PQ. MARIANO PICON SALAS', 'PQ. NARICUAL', 'PQ. BOQUERON', 'PQ. ZABALA', 'PQ. LA PUERTA', 'PQ. LA LUZ', 'PQ. MORON', 'PQ. SAN JOSE DE PERIJA', 'CM. ARAURE', 'PQ. TINAQUILLO', 'PQ. SAN ISIDRO LABRADOR', 'PQ. EL CHARAL', 'PQ. RIO SECO', 'PQ. CAZORLA', 'PQ. SAN ANTONIO LOS ALTOS', 'PQ.MCL.ANTONIO J DE SUCRE', 'PQ. TERESEN', 'PQ. ARISTIDES CALVANI', 'PQ. ANTIMANO', 'PQ. EL CALVARIO', 'PQ. PUNTA GORDA', 'PQ. GUARAUNOS', 'CM. PARIAGUAN', 'PQ. BARI', 'CM. BORAURE', 'PQ. UNIVERSIDAD', 'PQ. JORGE HERNANDEZ', 'PQ. CHACAO', 'PQ. ROMULO GALLEGOS', 'PQ. YAGUA', 'PQ. MANUEL P FAJARDO', 'CM. VILLA BRUZUAL', 'PQ. MARIA C PALACIOS', 'PQ. EL CARITO', 'PQ. UNARE', 'PQ. URICA', 'CM. GUANARITO', 'PQ. LAS GUACAMAYAS', 'PQ. GERONIMO MALDONADO', 'PQ. VALLE GUANAPE', 'PQ. GUARATARO', 'PQ. URIMARE', 'PQ. RAFAEL MARIA BARALT', 'PQ. SN FERNANDO DEL GUAPO', 'PQ. MESA BOLIVAR', 'PQ. CECILIO ZUBILLAGA', 'PQ. DORADAS', 'PQ. SANTA ANA', 'PQ. LOS TAQUES', 'PQ. TAGUAY', 'PQ. ATAPIRIRE', 'PQ. RIO CARIBE', 'PQ. GUAJIRA', 'PQ. COCHE', 'PQ. ELEAZAR LOPEZ C', 'PQ. PARAISO DE SAN JOSE', 'PQ. FERNANDEZ PEÑA', 'PQ. CHUAO', 'PQ. ASCENSION FARRERAS', 'PQ. PEÑALVER', 'PQ. AGUA LARGA', 'PQ. JOSE LEONARDO SUAREZ', 'PQ. GUARICO', 'PQ. EL BAUL', 'PQ. RAFAEL URDANETA', 'PQ. ISAIAS MEDINA ANGARIT', 'PQ. JUAN PABLO PEÑALOZA', 'PQ. FLORENCIO RAMIREZ', 'PQ. VALLES DE TUCUTUNEMO', 'CM. PUERTO PIRITU', 'PQ. RAUL LEONI', 'PQ. GUACARA', 'PQ. BEJUMA', 'PQ. SAN PEDRO', 'PQ. THERMO MORALES', 'PQ. SAN FCO. DE TIZNADOS', 'PQ. IRAPA', 'PQ. GENERAL RIVAS', 'PQ. UVERAL', 'PQ. MANUEL MANRIQUE', 'PQ. GRL/JEFE JOSE L SILVA', 'PQ. SANTA INES', 'PQ. LA TRAMPA', 'PQ. NICOLAS PULIDO', 'PQ. CUNAVICHE', 'PQ. LIBERTAD DE COJEDES', 'CM. SAN ANT DEL TACHIRA', 'PQ. JUAN MILLAN', 'CM. CAGUA', 'PQ. SIMON RODRIGUEZ', 'CM. EL TIGRE', 'PQ.ELEAZAR LOPEZ CONTRERA', 'PQ. CANOABO', 'PQ. CHAGUARAMAL', 'PQ. MOTATAN', 'PQ. LA GUAIRA', 'PQ. SAN JOSE', 'CM. SAN RAFAEL DE ONOTO', 'CM. CANTAURA', 'PQ. POZO VERDE', 'PQ. MARABAL', 'CM. QUIRIQUIRE', 'PQ. ARAGUANEY', 'PQ. LAS CALDERAS', 'PQ. URIBARRI', 'PQ. GUIRIPA', 'CM. COCOROTE', 'PQ. MIGUEL PEÑA', 'PQ. ACURIGUA', 'CM. SABANA DE PARRA', 'PQ. MASPARRITO', 'PQ. DOMINGO PEÑA', 'PQ. VISTA HERMOSA', 'PQ. VILLA ROSA', 'CM. INDEPENDENCIA', 'CM. BOCA DEL RIO', 'PQ. SABANA DE UCHIRE', 'PQ. AREO', 'CM. COLON', 'PQ. EL PARAISO', 'CM. CAPACHO VIEJO', 'PQ. STA TERESA DEL TUY', 'PQ. CARICUAO', 'PQ. ANTONIO DIAZ', 'PQ. GUANAGUANA', 'PQ. GUANAPE', 'PQ. LA TOSCANA', 'PQ. JOSE G. BASTIDAS', 'PQ. EL GUAPO', 'PQ. PUERTO CUMAREBO', 'PQ. CRISTO DE ARANZA', 'PQ. MONS FELICIANO G', 'PQ. EL GUACHARO', 'PQ. CUMBO', 'PQ. LUIS DE VICENTE', 'PQ. CATIA LA MAR', 'CM. BISCUCUY', 'PQ. EL DANTO', 'PQ. BUENA VISTA', 'PQ. LAS BRISAS', 'PQ. PASO REAL DE MACAIRA', 'PQ. TABASCA', 'PQ. MITARE', 'PQ. MANUEL FELIPE RUGELES', 'PQ. MORAN', 'CM. ARAGUA DE BARCELONA', 'PQ. SAN PEDRO DEL RIO', 'PQ. SAN FRANCISCO DE ASIS', 'PQ. LA MESA', 'CM. ARAGUA', 'CM. EL PALMAR', 'CM. MAPIRE', 'PQ. ALFREDO A LARRIVA', 'PQ. MANUEL MORILLO', 'PQ. EL CENIZO', 'CM. URACHICHE', 'CM. OSPINO', 'PQ. SAN LUIS', 'PQ. SABANA LIBRE', 'PQ. MARIARA', 'PQ. ELORZA', 'PQ. GUIGUE', 'PQ. SANTA FE', 'PQ. EL RECREO', 'PQ. LA ESPERANZA', 'PQ. TORUNOS', 'PQ. LA PEÑA', 'PQ. MARIÑO', 'PQ. HUMOCARO BAJO', 'PQ. PARHUEÑA', 'PQ. EL TEJERO', 'PQ.JOSE IGNACIO DEL PUMAR', 'PQ. VISTA AL SOL', 'PQ. EL CARTANAL', 'PQ. EL VINCULO', 'PQ. FREITEZ', 'CM. SAN ANTONIO', 'PQ. CAMACARO', 'PQ. MONS. MIGUEL A SALAS', 'PQ. ZARAZA', 'PQ. SORO', 'PQ. POTRERITOS', 'PQ. GIBRALTAR', 'PQ. FRANCISCO EUGENIO B', 'PQ. PETARE', 'CM. LA ASUNCION', 'PQ. SANTA CATALINA', 'PQ. URUMACO', 'PQ. EL BATEY', 'PQ. APARICIO', 'PQ. PAUJIL', 'PQ. MARCELINO BRICEÑO', 'PQ. CAMPO LARA', 'PQ. LA VEGA DE GUARAMACAL', 'PQ. HERIBERTO ARROYO', 'PQ. CUA', 'PQ. ACHAGUAS', 'PQ. LA SIERRITA', 'CM. SANTA ELENA DE UAIREN', 'PQ. URB SAN DIEGO', 'PQ. ALBARICO', 'PQ. QUINIMARI', 'PQ. ANZOATEGUI', 'PQ. GRAL FCO. A VASQUEZ', 'PQ. ANTONIO JOSE DE SUCRE', 'PQ. CUARA', 'PQ. LA GUANOTA', 'PQ. U TOCUYITO', 'PQ. GUEVARA', 'PQ. VENANCIO PULGAR', 'PQ. SANTA CLARA', 'PQ. LAS MERCEDES', 'PQ. JUAN B RODRIGUEZ', 'PQ. SAN RAFAEL DE A.', 'PQ. COLINA', 'CM. AROA', 'CM. GUAMA', 'PQ. SANTOS DE ABELGAS', 'PQ. SANTA MARIA DE IPIRE', 'CM. PALMIRA', 'PQ. SOUBLETTE', 'PQ. TAMACA', 'PQ. TRES DE FEBRERO', 'CM. SAN JOSECITO', 'PQ. SANTA ROSALIA', 'PQ. RIO NEGRO', 'PQ. PANAQUIRE', 'PQ. TIARA', 'PQ. JUAN JOSE FLORES', 'PQ. LASSO DE LA VEGA', 'PQ. EL PROGRESO', 'PQ. RIO ACARIGUA', 'CM. STA. ANA  DEL TACHIRA', 'PQ. EL SOCORRO', 'PQ. TAVERA ACOSTA', 'PQ. GUAIBACOA', 'PQ. EL MORRO', 'PQ. DIEGO DE LOZADA', 'PQ. CARRIZAL', 'PQ. SANTA APOLONIA', 'PQ. ANDRES BELLO', 'CM. LA GRITA', 'PQ. S ANTONIO DE YARE', 'PQ. SAN VICENTE', 'PQ. JOSE MARIA BLANCO', 'PQ. SAN FCO DE YARE', 'PQ. SIMON BOLIVAR', 'PQ. PALACIOS FAJARDO', 'CM. TUMEREMO', 'PQ. PEDRO BRICEÑO MENDEZ', 'PQ. TUÑAME', 'PQ. LA VICTORIA', 'PQ. PAMPANITO II', 'PQ. OLEGARIO VILLALOBOS', 'PQ. CUICAS', 'PQ. JOSE RAMON YEPEZ', 'PQ. ZUATA', 'PQ. CALDERAS', 'CM. DELICIAS', 'PQ. LAS VEGAS DEL TUY', 'PQ. CABURE', 'PQ. JUNIN', 'CM. BARRANCAS', 'PQ. AGUAS CALIENTES', 'PQ. SAN JOSE DE GUARIBE', 'PQ. SANTA TERESA', 'PQ. EL REGALO', 'PQ. LA CEIBA', 'PQ. LA CANDELARIA', 'PQ. CACHIPO', 'PQ. MUCUCHACHI', 'CM. SAN ANT DEL GOLFO', 'PQ. JOSE VIDAL MARCANO', 'PQ. CHACOPATA', 'PQ. MANICUARE', 'PQ. ARACUA', 'PQ. SN JUAN BAUTISTA', 'PQ. TOCUYO DE LA COSTA', 'PQ. MAMPORAL', 'PQ. ARENAS', 'PQ. SAN BERNARDINO', 'PQ. SAN ANDRES', 'PQ. FARIA', 'CM. TORONDOY', 'PQ. CARAYACA', 'PQ. EL PAUJI', 'PQ. JUAN A RODRIGUEZ D', 'PQ. TORRES', 'CM. SOLEDAD', 'PQ. CAUCAGUA', 'PQ. BARCELONETA', 'PQ. SAN JOSE DE AEROCUAR', 'CM. PAMPATAR', 'PQ. CHEREGUE', 'PQ. JUANA DE AVILA', 'CM. CHABASQUEN', 'PQ. BOROJO', 'PQ. BORBURATA', 'PQ. RIBAS', 'PQ. MARIZAPA', 'PQ. BARINITAS', 'PQ. PTE. ROMULO GALLEGOS', 'PQ. EL ROSARIO', 'PQ. FRANCISCO OCHOA', 'PQ. LA QUEBRADA', 'PQ. STA MARIA DEL HORCON', 'PQ. BARINAS', 'PQ. SAN JAVIER', 'PQ. EL CEDRO', 'PQ. NUEVA CUA', 'PQ. VALENTIN VALIENTE', 'PQ. SANTIAGO', 'PQ. AGUA VIVA', 'PQ. MANUEL SALVADOR ULLOA', 'PQ. SAN SILVESTRE', 'PQ. PECAYA', 'PQ. CHORONI', 'PQ. MOITACO', 'PQ. DOLORES', 'PQ. EL RINCON', 'CM. PALO NEGRO', 'PQ. JOSE FELIX RIBAS', 'CM. EL LIMON', 'CM. TEMBLADOR', 'PQ. PAYARA', 'PQ. TUNAPUY', 'PQ. MACARAPANA', 'PQ. CACIQUE MARA', 'CM. CAMATAGUA', 'PQ. PUEBLO NUEVO', 'PQ. MANUEL DAGNINO', 'PQ. JUAN DE MATA SUAREZ', 'PQ. LARA', 'PQ. EL CARMEN', 'PQ. S LORENZO DE TIZNADOS', 'PQ. SAN JUAN', 'PQ. CIUDAD ALIANZA', 'CM. UPATA', 'PQ. EL PINTO', 'CM. CORDERO', 'PQ. ESTANQUES', 'PQ. PEÑA BLANCA', 'CM. SAN FELIPE', 'PQ.SAN JUAN DE LOS MORROS', 'PQ. CHACANTA', 'PQ. PANAPANA', 'PQ. SANTA MARIA', 'PQ. MACUTO', 'CM. EL COBRE', 'PQ. LOS CORTIJOS', 'PQ. SAN FRANCISCO', 'PQ. TAGUAYA', 'PQ. PIAR', 'PQ. ANTONIO BORJAS ROMERO', 'PQ. HERAS', 'PQ. SIXTO ZAMBRANO', 'PQ. LUIS ALBERTO GOMEZ', 'CM. SAN JOSE DE GUANIPA', 'PQ. CAMPO ALEGRE', 'PQ.SAN JOSE DE LA MONTAÑA', 'PQ. CUPIRA', 'PQ. EL BAJO', 'PQ. LA PUEBLITA', 'PQ. CARRILLO', 'CM. ABEJALES', 'PQ. VALMORE RODRIGUEZ', 'PQ. LA TRINIDAD', 'PQ. PEDRO COVA', 'PQ. RAMON IGNACIO MENDEZ', 'CM. MARIPA', 'CM.LA PLAZA DE PARAGUACHI', 'CM. SAN SIMON', 'PQ. JAJI', 'PQ. AMBROSIO', 'PQ. JUAN VICENTE GOMEZ', 'PQ. SINAMAICA', 'PQ. LOS BARALES', 'CM. SANTO DOMINGO', 'PQ. LA UNION', 'PQ. JACINTO PLAZA', 'PQ. SEQUE', 'PQ. LA CIENAGA', 'PQ. RICAURTE', 'PQ.SAN JUAN GUANAGUANARE', 'PQ. EL CARMELO', 'PQ. PUERTO VIVAS', 'PQ. MENDOZA', 'PQ. ALTOS DE LOS GODOS', 'PQ. CARIRUBANA', 'PQ. SAN GABRIEL', 'PQ. CARIACO', 'PQ. SAN CARLOS DE AUSTRIA', 'PQ. ARIPAO', 'PQ. AREVALO APONTE', 'PQ. SAN CRISTOBAL', 'PQ. CABRUTA', 'PQ. CARMEN HERRERA', 'PQ. MANTECAL', 'PQ. BELEN', 'PQ. CARUAO', 'PQ. QUINTERO', 'PQ. CHARALLAVE', 'PQ. EL HATO', 'PQ. DOMINGA ORTIZ P', 'PQ. BELLA VISTA', 'PQ. MUCUTUY', 'PQ. PUEBLO CUMAREBO', 'PQ. ALTAMIRA', 'PQ. SN RAFAEL DE ATAMAICA', 'PQ. GERMAN RIOS LINARES', 'PQ. CAÑO DELGADITO', 'PQ. BOLIVIA', 'PQ. GABRIEL PICON G.', 'PQ. LA ESTACION', 'PQ. LAS PARCELAS', 'PQ. EL MOLINO', 'CM. LA AZULITA', 'CM. PUERTO LA CRUZ', 'PQ. UNION', 'PQ. ANTOLIN TOVAR AQUINO', 'PQ. SAN JUAN DE LOS CAYOS', 'PQ. MILLA', 'PQ. UVERITO', 'CM. GUANARE', 'PQ. CHEJENDE', 'PQ. SAN ISIDRO', 'CM. SAN SEBASTIAN', 'PQ. IDELFONZO VASQUEZ', 'PQ. SAN FELIX', 'PQ. SAN TIMOTEO', 'CM. PALMASOLA', 'PQ. LEZAMA', 'PQ. LA VELA DE CORO', 'CM. COLONCITO', 'PQ. CRUZ CARRILLO', 'PQ. SAN RAFAEL'}
    JSON_states={'Yaracuy', 'Delta Amacuro', 'Aragua', 'Nueva Esparta', 'Sucre', 'Bolívar', 'Táchira', 'Portuguesa', 'Amazonas', 'Falcón', 'Cojedes', 'Carabobo', 'La Guaira', 'Trujillo', 'Apure', 'Guárico', 'Zulia', 'Monagas', 'Lara', 'Mérida', 'Miranda', 'Barinas', 'Anzoátegui', 'Distrito Capital'}
    JSON_munips={'El Hatillo', 'Monte Carmelo', 'Campo Elías', 'Bolívar', 'Diego Ibarra', 'Libertad', 'Cruz Paredes', 'Jesús María Semprum', 'Valencia', 'Antolín del Campo', 'Cardenal Quintero', 'Mario Briceño Iragorri', 'San Judas Tadeo', 'Tovar', 'Autónomo Atabapo', 'Unión', 'Carrizal', 'Macanao', 'Urachiche', 'Pedro Zaraza', 'Francisco del Carmen Carvajal', 'Cocorote', 'Aguasay', 'Andrés Mata', 'Francisco Linares Alcántara', 'Jáuregui', 'San Joaquín', 'La Trinidad', 'Urumaco', 'San Rafael de Onoto', 'Autónomo Atures', 'Muñoz', 'Petit', 'Santiago Mariño', 'Papelón', 'Torbes', 'Obispos', 'Antonio Rómulo Costa', 'Bocono', 'Juan Antonio Sotillo', 'Falcón', 'Aricagua', 'Juan Vicente Campo Elías', 'Escuque', 'Jacura', 'Moran', 'Casacoima', 'Guacara', 'Santos Marquina', 'Mariño', 'Santa Rosalía', 'Catatumbo', 'Justo Briceño', 'Rangel', 'Caripe', 'Ortiz', 'Monseñor José Vicente de Unda', 'San Juan de Capistrano', 'Acosta', 'Cabimas', 'Caracciolo Parra Olmedo', 'Miranda', 'San Francisco', 'Monagas', 'Barinas', 'Santos Michelena', 'Ayacucho', 'Pao de San Juan Bautista', 'José Antonio Páez', 'Buchivacoa', 'Palmasola', 'Díaz', 'Manapiare', 'García', 'Tulio Febres Cordero', 'Arzobispo Chacón', 'Santa María de Ipire', 'Sucre', 'Federación', 'Tucupita', 'Tinaquillo', 'Bruzual', 'Seboruco', 'Arístides Bastidas', 'Guanarito', 'Ospino', 'San Genaro de Boconoito', 'Cárdenas', 'Padre Pedro Chien', 'Sosa', 'Montalbán', 'Colina', 'Alberto Adriani', 'Baruta', 'Girardot', 'Palavecino', 'Manuel Ezequiel Bruzual', 'Autónomo Alto Orinoco', 'Sotillo', 'Rómulo Gallegos', 'Carache', 'Mara', 'Maracaibo', 'Córdoba', 'Nirgua', 'Cedeño', 'Los Taques', 'El Socorro', 'Sir Arthur Mc Gregor', 'Leonardo Infante', 'Zea', 'Simón Bolívar', 'José Rafael Revenga', 'Uracoa', 'Andrés Eloy Blanco', 'Trujillo', 'San Casimiro', 'Camatagua', 'Valmore Rodríguez', 'Santa Ana', 'San Gerónimo de Guayabal', 'Colon', 'Guasimos', 'Almirante Padilla', 'El Callao', 'Esteller', 'Julián Mellado', 'Antonio Pinto Salinas', 'Maneiro', 'Pedro Camejo', 'José Ángel Lamas', 'Autónomo Maroa', 'Carirubana', 'Gómez', 'Mauroa', 'Agua Blanca', 'Candelaria', 'Independencia', 'Gran Sabana', 'Puerto Cabello', 'Panamericano', 'Diego Bautista Urbaneja', 'Veroes', 'Democracia', 'Montes', 'Juan José Mora', 'Punceres', 'Cajigal', 'Bejuma', 'Iribarren', 'Benítez', 'Turen', 'Machiques de Perija', 'Vargas', 'García de Hevia', 'Santa Rita', 'Francisco de Miranda', 'Naguanagua', 'Páez', 'Camaguan', 'San José de Guanipa', 'San Cristóbal', 'Arismendi', 'Simón Planas', 'La Cañada de Urdaneta', 'Juan Germán Roscio', 'Araure', 'Francisco Javier Pulgar', 'Tinaco', 'Uribante', 'Autónomo Rio Negro', 'Ribero', 'San Diego', 'Torres', 'Bolivariano Guaicaipuro', 'Marcano', 'José Felipe Márquez Cañizal', 'Pedernales', 'Indígena Bolivariano Guajira', 'Acevedo', 'Simón Rodríguez', 'Bolivariano Angostura', 'Mejía', 'Samuel Darío Maldonado', 'San Sebastián', 'Biruaca', 'Fernández Feo', 'Sifontes', 'Manuel Monge', 'Roscio', 'Fernando de Peñalver', 'Villalba', 'Valera', 'Julio Cesar Salas', 'Rafael Rangel', 'Los Guayos', 'Antonio Díaz', 'Pueblo Llano', 'Guanta', 'Juan Manuel Cajigal', 'Baralt', 'Pedraza', 'Tocopero', 'Jiménez', 'Las Mercedes', 'Pedro María Freites', 'Bermúdez', 'Anzoátegui', 'Padre Noguera', 'Dabajuro', 'Crespo', 'Autónomo Autana', 'Chacao', 'Plaza', 'Ocumare de la Costa de Oro', 'Aragua', 'San José de Guaribe', 'Jesús Enrique Lossada', 'Guaraque', 'Valdez', 'Ezequiel Zamora', 'Buroz', 'Rosario de Perija', 'José María Vargas', 'Alberto Arvelo Torrealba', 'Angostura del Orinoco', 'Rojas', 'Piar', 'Cacique Manaure', 'José Félix Ribas', 'Piritu', 'Pedro Gual', 'Cristóbal Rojas', 'Lagunillas', 'Santa Barbara', 'Guanare', 'Urdaneta', 'Michelena', 'Libertador', 'Lander', 'Zamora', 'Pedro María Ureña', 'Peña', 'Ricaurte', 'Paz Castillo', 'San Rafael de Carvajal', 'Andrés Bello', 'Obispo Ramos de Lora', 'Rivas Dávila', 'Rafael Urdaneta', 'Junín', 'Cruz Salmerón Acosta', 'Caroní', 'Pampan', 'Antonio José de Sucre', 'Monseñor Iturriza', 'Lima Blanco', 'Achaguas', 'Pampanito', 'San Felipe', 'Motatan', 'Lobatera', 'Silva', 'Carlos Arvelo', 'Brión', 'Anaco', 'La Ceiba', 'Tubores', 'Chaguaramas', 'Maturín', 'Los Salías', 'San Fernando'}
    JSON_parroquias={'El Hatillo', 'Urbana Bruzual', 'La Aguadita', 'Moruy', 'Santa Cruz', 'Luis Alberto Gómez', 'Barinitas', 'Jorge Hernández', 'Masparrito', 'Parhueña', 'Pulido Méndez', 'Arias', 'Campo Elías', 'Cristóbal Mendoza', 'Capital Tucupido', 'Catuaro', 'No Urbana Negro Primero', 'Unión', 'San Cristóbal de Torondoy', 'Mariscal Antonio José de Sucre', 'No Urbana Ollas de Caramacate', 'Francisco Aniceto Lugo', 'Urbana San Joaquín', 'Guajiro', 'Reyes Vargas', 'No Urbana  Alfredo Pacheco Miranda', 'Capital Valle de la Pascua', 'La Ciénaga', 'Capital Arismendi', 'Jáuregui', 'Peñalver', 'Corazón de Jesús', 'San Joaquín', 'Bartolomé de las Casas', 'Concepción', 'El Vinculo', 'San José de Tiznados', 'José Ignacio del Pumar Pedraza', 'Urbana las Delicias', 'La Estación', 'Trinidad Samuel', 'Obispos', 'Aricagua', 'Puerto la Cruz', 'La Venta', 'El Yagual', 'Urbana San José', 'El Progreso', 'La Guaira', 'Capital San Genaro de Boconoito', 'La Palmita', 'Cumbo', 'Mavaca', 'Santa Rosa', 'Uvencio Antonio Velásquez', 'Cruz Carrillo', 'Capital Cedeño', 'San Francisco de Macaira', 'Yaguaraparo', 'Mucuritas', 'San Francisco', 'Las Alhuacas', 'Emilio Constantino Guerrero', 'Monagas', 'Puerto Santo', 'Guarenas', 'Barinas', 'La Beatriz', 'Guachara', 'Tres Esquinas', 'Caucaguita', 'Moitaco', 'No Urbana Canoabo', 'General En Jefe José Laurencio Silva', 'Arévalo González', 'Capital Bolívar', 'Guainiamo', 'Teresen', 'Juan Millán', 'Trinidad de la Capilla', 'Raúl Leoni', 'Catedral', 'Manuel Manrique', 'Boca de Chávez', 'Betijoque', 'Adicora', 'Chejende', 'Aguedo Felipe Alvarado', 'Piedra Grande', 'Boca de Aroa', 'El Charal', 'Maiquetía', 'Hernández', 'Rómulo Gallegos', 'Carache', 'Vista Hermosa', 'Vista Al Sol', 'Tocuyo de la Costa', 'Córdoba', 'Manuel Felipe Rugeles', 'Los Taques', 'Uveral', 'Jajo', 'Capital Guaraque', 'Aparicio', 'Capital Piritu', 'Leoncio Martínez', 'Agua Larga', 'Baraived', 'La Democracia', 'Puerto Vivas', 'Cachipo', 'Camatagua', 'Carrillo', 'El Baño', 'José Antonio Chaves', 'Santa Cruz del Zulia', 'Caracciolo Parra Perez', 'Aripao', 'Guadarrama', 'Capital Juan Manuel Cajigal', 'Araguita', 'Carirubana', 'Marizapa', 'Lara', 'Capital Antolín del Campo', 'Ribas', 'Santo Domingo', 'Capital Arzobispo Chacón', 'Gerónimo Maldonado', 'Las Parcelas', 'Pueblo Cumarebo', 'Capital Ortiz', 'Santa Barbará', 'Francisco Ochoa', 'Urbana Unión', 'Las Vegas Del tuy', 'Isaías Medina Angarita', 'Monseñor Carrillo', 'Ticoporo', 'Humocaro Bajo', 'Zazarida', 'Pueblo Nuevo', 'Dominga Ortiz de Páez', 'Virgen del Valle', 'San Pedro del Rio', 'Torunos', 'No Urbana Simón Bolívar', 'Francisco de Miranda', 'Cecilio Acosta', 'Pedro Briceño Méndez', 'No Urbana Carmen de Cura', 'Las Minas de Baruta', 'Arismendi', 'Paracotos', 'San Rafael de Palo Alzado', 'Las Piedras', 'Charallave', 'Juan Germán Roscio', 'Capital Gómez', 'Villa Rosa', 'Altagracia', 'San Benito', 'Pedernales', 'Rio Chico', 'Rio Acarigua', 'Santa Apolonia', 'Simón Rodríguez', 'Puerto Miranda', 'Faria', 'Rincón Hondo', 'San Isidro', 'Pedregal', 'Altagracia de la Montaña', 'Santa Fe', 'General Francisco Antonio Vásquez', 'Guárico', 'San Camilo', 'Mantecal', 'Quintero', 'Urimare', 'Olegario Villalobos', 'La Toma', 'Capital Veroes', 'Capital Rangel', 'Sabana de Piedra', 'Dabajuro', 'San Lorenzo', 'La Paz', 'San José de Guaribe', 'Capital Peña', 'No Urbana Samán de Guere', 'Capital Pedro María Freites', 'San José de Saguaz', 'La Petrolea', 'San Diego de Cabrutica', 'Ramón Peraza', 'Curimagua', 'Capital Altagracia de Orituco', 'San Silvestre', 'El Pilar', 'Piritu', 'Román Cárdenas', 'Tamaca', 'Padre Barral', 'Capital San Felipe', 'Los Nevados', 'No Urbana Arévalo Aponte', 'Guaibacoa', 'No Urbana Belen', 'Arenas', 'Rómulo Betancourt', 'Constitución', 'San Rafael de Alcázar', 'La Vela de Coro', 'Adaure', 'Cocuy', 'Andrés Bello', 'Capital las Mercedes', 'Pampan', 'Amenodoro Rangel Lamus', 'Jaji', 'Seque', 'San Antonio', 'La Sabanita', 'San Juan Bautista', 'Pampanito', 'Guayapo', 'Caruao', 'Rio Negro', 'Capital Guasimos', 'Espinoza de los Monteros', 'Lobatera', 'Temerla', 'Pedro Lucas Urribarri', 'Santa Bárbara', 'San José de la Costa', 'No Urbana Pao de Zarate', 'La Victoria', 'Capital Guanarito', 'Caraballeda', 'Parapara', 'San Fernando', 'Raúl Leoni los Puertos de Santa Fé', 'Irapa', 'No Urbana San Martin de Porres', 'Capital Punceres', 'Cabruta', 'Xaguas', 'San Joaquín de Navay', 'Manicuare', 'Sixto Zambrano', 'Salom', 'Libertad', 'Agua Clara', 'Jesús María Semprum', 'General Rivas', 'Capital Páez', 'Urbana los Guayos', 'Mesa de Quintero', 'Churuguara', 'Las Calderas', 'El Blanco', 'Urbana Andrés Eloy Blanco', 'Tacarigua', 'Los Cedros', 'La Trinidad', 'Tabasca', 'El Rosario', 'El Pinto', 'Agua Caliente', 'Germán Ríos Linares', 'Santa Cruz de Guacas', 'Capital el Callao', 'Universidad', 'Santiago Mariño', 'Miguel Otero Silva', 'El Amparo', 'Urbana San Fernando de Apure', 'Cipriano Castro', 'Juan Pablo Peñaloza', 'San Timoteo', 'Urbana fraternidad', 'Santa Rosalía', 'Mariano Parra León', 'Soro', 'Puerto Cumarebo', 'El Paují', 'Marhuanta', 'Monagas', 'Juan Rodríguez Suarez', 'Guevara', 'Bobures', 'Capital Michelena', 'Las Cocuizas', 'La Soledad', 'Sabana Grande', 'Ayacucho', 'La Pica', 'Urbana Juan José Flores', 'Chirica', 'La Concordia', 'Capital Cardenal Quintero', 'Tunapuicito', 'El Carito', 'Dalla Costa', 'Maparari', 'Capital Francisco del Carmen Carvajal', 'Arístides Bastidas', 'Agua Linda', 'Apurito', 'Pecaya', 'Santa Rita de Manapire', 'Cárdenas', 'Sinamaica', 'Capital José Ángel Lamas', 'San Andrés', 'Capital Aricagua', 'Avaria', 'Colina', 'San Pedro', 'Alberto Adriani', 'Capital Santa Rosalía', 'Urbana Elorza', 'Urbana Mariara', 'Tavera Acosta', 'El Paujil', 'Sabaneta', 'Punta Gorda', 'Punta de Piedras', 'Siquisique', 'Curiepe', 'Úrica', 'Pueblo Nuevo del Sur', 'Nirgua', 'Capital Tubores', 'Urbana Candelaria', 'El Valle', 'Capaya', 'La Rosa', 'Santa Ana', 'Alonso de Ojeda', 'La Puerta', 'Buria', 'Cacique Mara', 'Guaraunos', 'Gabriel Picón González', 'Mamo', 'San Fernando del Guapo', 'Candelaria', 'Florida', 'El Rincón', 'Guasimitos', 'Rivas Berti', 'Urbana Aguas Calientes', 'Queseras del Medio', 'Curiapo', 'Boca de Tocuyo', 'San Félix', 'Araguaney', 'Los Teques', 'Cabudare', 'Urbana Pedro José Ovalles', 'El Baúl', 'Cabo José Dorante', 'José Vidal Marcano', 'El Guácharo', 'Pampanito Ii', 'No Urbana Patanemo', 'Capital Piar', 'El Cují', 'Viento Fresco', 'Bideau', 'Tacarigua de la Laguna', 'Santa Rita', 'Camaguan', 'Páparo', 'Matriz', 'Chorrerón', 'Capital Marcano', 'Potosí', 'Los Barales', 'El Guapo', 'Capuri', 'Aparición', 'Capital José Rafael Revenga', 'El Junquito', 'Urbana Miranda', 'Rio Caribe', 'Uribante', 'San Miguel', 'Torres', 'Cua', 'Nuestra Señora del Rosario de Baruta', 'Urbana Caña de Azúcar', 'Domitila Flores', 'Huachamacare', 'Samuel Darío Maldonado', 'San Sebastián', 'No Urbana Borburata', 'José Leonardo Suarez', 'Paraíso de San José', 'Alto Barinas', 'Taguaya', 'Capital Guanare', 'Cegarra', 'Manuel Guanipa Matos', 'Chichiriviche', 'Edmundo Barrios', 'No Urbana Valles de Tucutunemo', 'Pueblo Llano', 'San Rafael', 'Quebrada Honda de Guache', 'Imataca', 'Dr. Francisco Romero Lobo', 'Encontrados', 'San Javier', 'Cristóbal Colon', 'Anzoátegui', 'Urbana Tocuyito', 'Campo Alegre', 'El Mene', 'Tomas Alfaro Calatrava', 'Platanillal', 'Manuel Dagnino', 'Urbana Rafael Urdaneta', 'Capital Justo Briceño', 'Capital García', 'Mucutuy', 'Juana de Ávila', 'Sarare', 'Piar', 'Venezuela', 'Cristo de Aranza', 'Payara', 'Capital Ezequiel Zamora', 'Capital Diego Bautista Urbaneja', 'Pio Tamayo', 'Capital Monseñor José Vicente de Unda', 'La Toscana', 'María de la Concepción Palacios Blanco', 'Petare', 'Capital Sucre', 'Hilario Luna y Luna', 'El Llano', 'La Peña', 'Calderas', 'Tunapuy', 'Pedro María Ureña', 'Urribarri', 'El Tejero', 'Carvajal', 'Antonio Borjas Romero', 'Capital el Sombrero', 'Chiguara', 'San Juan de los Cayos', 'Rafael Urdaneta', 'Urbana Montalbán', 'Capital Santa María de Ipire', 'Junín', 'José Domingo Rus', 'Ocumare del Tuy', 'Cumanacoa', 'Guanaguana', 'Luis Beltrán Prieto Figueroa', 'Capital Córdoba', 'Los Caprichos', 'Guardatinajas', 'Machurucuto', 'San Antonio de Yare', 'No Urbana San Francisco de Cara', 'Cabimbu', 'José Gregorio Hernández', 'No Urbana Bella Vista', 'Florencio Ramírez', 'Purureche', 'Guanape', 'Cantagallo', 'Capital Maneiro', 'Soublette', 'Nueva Arcadia', 'El Rastro', 'Juan Antonio Rodríguez Domínguez', 'Capital Obispo Ramos de Lora', 'Cheregue', 'La Quebrada', 'Bajo Ventuari', 'San Carlos de Austria', 'Monte Carmelo', 'Cupira', 'Capital Papelón', 'Bolívar', 'Pijiguaos', 'Orinoco', 'Acurigua', 'No Urbana Yagua', 'Libertad de Cojedes', 'Doradas', 'San Judas Tadeo', 'Carrizal', 'Mercedes Díaz', 'Sierra Parima', 'Flor de Patria', 'Rodríguez Domínguez', 'Cocorote', 'Aguasay', 'Francisco Linares Alcántara', 'José Ramón Yepez', 'Almirante Luis Brión', 'Cecilio Zubillaga', 'Urumaco', 'Espino', 'Ciudad de Nutrias', 'Guaimaral', 'No Urbana Francisco de Miranda', 'San José de Bolívar', 'No Urbana San Francisco de Asís', 'Sabana de Mendoza', 'Torbes', 'Monseñor Arturo Celestino Álvarez', 'Capital Pinto Salinas', 'Agua Viva', 'Rendón', 'Juan Vicente Gómez', 'Vega de Guaramacal', 'Cacute', 'Santa Inés', 'Urbana Joaquín Crespo', 'Araurima', 'Panapana', 'Moran', 'Capital Libertad', 'Capital San Sebastián', 'Montaña Verde', 'Altamira', 'Santos Marquina', 'Capital Villalba', 'Ana María Campos', 'Gonzalo Picón Febres', 'Milla', 'Manuel Salvador Ulloa', 'Santa Isabel', 'Urbana Juan Vicente Bolívar y Ponte', 'Marabal', 'Mosquey', 'Capital Angostura', 'Antolín Tovar Aquino', 'San Francisco de Yare', 'Mamporal', 'Capital Araure', 'No Urbana Guiripa', 'La Unión', 'Capital Cedeño', 'San Luis', 'Rio Seco', 'Sucre', 'Castañeda', 'El Dividive', 'Jusepín', 'Catia la Mar', 'Zabala', 'Presidente Betancourt', 'Agua Santa', 'El Bajo', 'La Urbana', 'Sosa', 'Macoruca', 'Montalbán', 'Santa Teresa', 'Yacapana', 'Diego de Lozada', 'Campo Claro', 'Nicolás Pulido', 'Urbana Naguanagua', 'San Isidro Labrador', 'San José del Sur', 'El Socorro', 'No Urbana Tiara', 'Pedro Cova', 'Simón Bolívar', 'Capital Mejía', 'Capital Díaz', 'Areo', 'Monseñor Jáuregui', 'Urbana Castor Nieves Ríos', 'Monseñor Marcos Sergio Godoy', 'Andrés Eloy Blanco', 'Juan Ángel Bravo', 'Santa María', 'Caname', 'Casiquiare', 'Cuara', 'Barceloneta', 'Buena Vista', 'Macapo', 'San Francisco de Tiznados', 'Sabana de Uchire', 'Aracua', 'Guaramacal', 'Capital Padre Pedro Chien', 'Mario Briceño Iragorry', 'Panamericano', 'Domingo Peña', 'Higuerote', 'Cabure', 'Chacanta', 'San José de Aerocuar', 'Nueva Cua', 'Carmen Herrera', 'Bari', 'El Carmelo', 'Héctor Amable Mora', 'Guarataro', 'Presidente Páez', 'Vargas', 'San Cristóbal', 'Chiquinquira', 'Agua Salada', 'José María Blanco', 'Urbana Catedral', 'Puerto de Nutrias', 'Valentín Valiente', 'Francisco Javier Pulgar', 'Mesa de Bolívar', 'Filas de Mariches', 'Capital Andrés Bello', 'Mucuruba', 'San José de Barlovento', 'Burbusay', 'No Urbana Choroni', 'Mendoza', 'Alfredo Arvelo Larriva', 'Boquerón', 'Capital Sotillo', 'Mesa de las Palmas', 'Tacata', 'Fernández Feo', 'Coche', 'Guatire', 'Manuel Monge', 'Carayaca', 'Fernando de Peñalver', 'Manuel Piar', 'Manuel Palacio Fajardo', 'Rafael Rangel', 'Capital Manuel Ezequiel Bruzual', 'Carlos Soublette', 'Tocopero', 'Humocaro Alto', 'Las Mercedes', 'Chacao', 'Fernando Giron Tovar', 'El Jarillo', 'Urbana Bartolomé Salom', 'Urbana Goaigoaza', 'San José de Perija', 'Delicias', 'Capital San José de Guanipa', 'El Guayabo', 'Capital Ospino', 'Albarico', 'Quinimari', 'Venancio Pulgar', 'No Urbana Guigue', 'Monseñor Argimiro García', 'Bariro', 'Andrés Linares', 'José Félix Ribas', 'Cinco de Julio', 'No Urbana Augusto Mijares', 'Capital San Gerónimo de Guayabal', 'Santa Clara', 'Capital Piar', 'Boca del Pao', 'San Rafael de Orituco', 'Urdaneta', 'Osuna Rodríguez', 'Boconó', 'El Cenizo', 'Presidente Rómulo Gallegos', 'Libertador', 'Bolivia', 'Fernández Peña', 'No Urbana Magdaleno', 'Ricaurte', 'Gran Mariscal los Altos de Sucre', 'Antonio Nicolás Briceño', 'No Urbana Taguay', 'Matasiete', 'La Trampa', 'Cojedes', 'El Recreo', 'Juan de Mata Suarez', 'Alto Ventuari', 'Urbana Biruaca', 'Tres de Febrero', 'El Corozo', 'La Pueblita', 'El Batey', 'Santa Cruz de Bucaral', 'José Nucete Sardi', 'Santa Lucia', 'Freitez', 'San Juan', 'El Carmen', 'No Urbana las Peñitas', 'Samariapo', 'San Juan de Guanaguanare', 'La Ceiba', 'San José', 'Uverito', 'Unare', 'Chaguaramas', 'La Pastora', 'Ignacio Briceño', 'Capital Gran Sabana', 'Pozuelos', 'Cuicas', 'Heras', 'Urbana Santa Rosa', 'Thermo Morales', 'Capital Sifontes', 'Bergantín', 'Arístides Calvani', '23 de Enero', 'Valerita', 'Leonardo Ruiz Pineda', 'Mitare', 'Juan Ignacio Montilla', 'Atapirire', 'Medio Ventuari', 'Caño el Tigre', 'Capatarida', 'Vicente Fuentes', 'Divina Pastora', 'Tovar', 'Mene de Mauroa', 'Alto de los Godos', 'San Agustín', 'Urachiche', 'No Urbana Urama', 'Codazzi', 'Las Brisas', 'Urbana Guacara', 'Antimano', 'Urbana San Diego', 'Munduapo', 'Borojo', 'Donaldo García', 'Lasso de la Vega', 'Tintorero', 'Coronel Mariano Peraza', 'El Furrial', 'Araya', 'No Urbana Monseñor Feliciano González', 'Norte', 'Santiago', 'Marawaka', 'Bocono', 'Idelfonso Vásquez', 'Luis Hurtado Higuera', 'Naiguata', 'La Florida', 'Jacura', 'El Café', 'Escuque', 'Juan Bautista Arismendi', 'Urbana Democracia', 'Punta Cardón', 'Mariño', 'Ciudad Bolivia', 'Barrancas', 'Macarao', 'Urbana José Casanova Godoy', 'Caño Delgadito', 'San Vicente', 'El Regalo', 'Capital Calabozo', 'Juárez', 'Canelones', 'Jacinto Plaza', 'Macuto', 'Montes de Oca', 'Palacios Fajardo', 'Tamare', 'La Candelaria', 'Capital Turén', 'Caigua', 'Santos Michelena', 'El Hato', 'José Antonio Páez', 'Palmasola', 'Guajira', 'Don Rómulo Betancourt', 'Cunaviche', 'Urbana el Socorro', 'Tinaquillo', 'Bruzual', 'El Jaguito', 'Luis de Vicente', 'Gibraltar', 'Capital Acosta', 'Capital Península de Macanao', 'Campo Lara', 'Capital Mariño', 'San Pablo', 'Cariaco', 'Capital Miranda', 'Coquivacoa', 'Los Barrancos de Fajardo', 'San Bernandino', 'Aguirre', 'Caricuao', 'Capital San Rafael de Onoto', 'Macarapana', 'Adrian', 'José Gregorio Bastidas', 'Pedro María Morantes', 'Virgen de la Coromoto', 'No Urbana Tacarigua Central', 'Yacambu', 'Capital Caripe', 'Emeterio Ochoa', 'Zea', 'Urbana Independencia', 'La Mesa', 'Santa María del Horcon', 'El Danto', 'Capital San Juan de Capistrano', 'Urbana Achaguas', 'Urbana Bejuma', 'Uracoa', 'El Real', 'Marcelino Briceño', 'Isla de Toas', 'San Casimiro', 'El Morro', 'Palmira', 'Valmore Rodríguez', 'Tucacas', 'Palotal', 'Mariano Picón Salas', 'Udon Perez', 'Monseñor Miguel Antonio Salas', 'Capital Rivas Dávila', 'Rafael María Baralt', 'Eleazar López Contreras', 'Libertad de Orituco', 'Estanquez', 'Cocollar', 'Sabana Libre', 'Capital Zea', 'Independencia', 'San José de la Montaña', 'Capital Sucre', 'San Antonio de Irapa', 'Zuata', 'Pimpinela', 'Pozo Verde', 'El Molino', 'Capital Seboruco', 'Yocoima', 'Chaguaramal', 'La Guanota', 'Granados', 'Mucuchachi', 'Sipapo', 'Guiria', 'La Esperanza', 'Capital Sir Arthur Mc Gregor', 'José Cenovio Urribarri', 'No Urbana Zuata', 'No Urbana las Guacamayas', 'García de Hevia', 'Panamericana', 'Moralito', 'Acequias', 'Páez', 'San José de Unare', 'San Lorenzo de Tiznados', 'Capital Caracciolo Parra Olmedo', 'Boca de Grita', 'Elías Sánchez Rubio', 'El Paraíso', 'San Rafael de Laya', 'Urbana Ciudad Alianza', 'San Gabriel', 'La Dolorita', 'El Cartanal', 'Ucata', 'Lezama', 'Alta Guajira', 'Urbana Morón', 'Francisco Eugenio Bustamante', 'Urbana Madre María de San José', 'Moroturo', 'La Vega', 'Gustavo Vegas León', 'El Calvario', 'Los Cortijos', 'La Sierrita', 'General Urdaneta', 'San Juan de las Galdonas', 'Bramon', 'Antonio Díaz', 'Capital Zaraza', 'Guanta', 'Peña Blanca', 'Camacaro', 'Ambrosio', 'Cazorla', 'Capital Tovar', 'Capital Roscio', 'Arnoldo Gabaldon', 'Raúl Cuenca', 'Padre Noguera', 'Francisco Fajardo', 'El Junko', 'Ikabaru', 'Jalisco', 'El Cafetal', 'No Urbana Valle Morín', 'El Pao', 'Ocumare de la Costa de Oro', 'Aragua', 'Cachamay', 'La Concepción', 'Ezequiel Zamora', 'Las Majadas', 'Santos de Abelgas', 'Capital Agua Blanca', 'Caucagua', 'Santa Catalina', 'Cacique Manaure', 'San Juan de Payara', 'Urbana los Tacariguas', 'Piñango', 'Urbana Guasdualito', 'Marcial Hernández', 'Sagrario', 'Eloy Paredes', 'Capadare', 'La Luz', 'Guzmán Guillermo', 'Panaquire', 'Manuel Morillo', 'Chacopata', 'Ascensión Farreras', 'San Simón', 'Naricual', 'Capital Tulio Febres Cordero', 'El Morro de Puerto Santo', 'Casigua', 'Dolores', 'Santa Teresa del Tuy', 'Judibana', 'El Cantón', 'Manuel Renaud', 'Carlos Quevedo', 'San Rafael de Atamaica', 'Urbana San Blas', 'No Urbana Chuao', 'Once de Abril', 'Capital Libertador', 'Jadacaquiva', 'Paso Real de Macaira', 'Capital Esteller', 'Antonio José de Sucre', 'San Carlos del Zulia', 'Potreritos', 'Capital Maturín', 'Antonio Spinetti Dini', 'Antonio Rómulo Acosta', 'Urbana Miguel Peña', 'San Antonio de los Altos', 'Motatan', 'Anaco', 'Capital San Juan de los Morros', 'Juan Bautista Rodríguez', 'Comunidad', 'Juan de Villegas', 'Solano', 'Ramón Ignacio Méndez', 'Tuñame'}


    # now loop through CSV_states, convert using states_mapping and verify that the result is in JSON_states
    for c_state in CSV_states:
        assert c_state in states_mapping, f'{c_state} not found in states_mapping'
        j_state = states_mapping[c_state]
        assert j_state in JSON_states, f'{j_state} not found in JSON_states'
        
    for c_munip in CSV_munips:
        assert c_munip in municipalities_mapping, f'{c_munip} not found in munips_mapping'
        j_munip = municipalities_mapping[c_munip]
        assert j_munip in JSON_munips, f'{j_munip} not found in JSON_munips'

    errors = 0
    good = 0
    from unidecode import unidecode
    #remove 'Urbana ' and 'No Urbana ' prefixes
    JSON_parroquias = set([k[7:] if k.startswith('Urbana ') else k for k in JSON_parroquias])
    JSON_parroquias = set([k[10:] if k.startswith('No Urbana ') else k for k in JSON_parroquias])
    #remove "capital " prefix
    JSON_parroquias = set([k[8:] if k.startswith('Capital ') else k for k in JSON_parroquias])
    JSON_parroquias_normalized = {unidecode(k.lower().strip()) for k in JSON_parroquias}
    for c_parish in CSV_parroquias:
        assert c_parish in parroquias_mapping, f'{c_parish} not found in parroquias_mapping'
        j_parish_o = parroquias_mapping[c_parish]
        j_parish = unidecode(j_parish_o.lower().strip())
        try:
            assert j_parish in JSON_parroquias_normalized, f'{j_parish} not found in JSON_parroquias'
            good += 1
        except Exception as e:
            errors += 1
            print(f'Error: {e}')
    print(f'Errors: {errors}, Good: {good}, {good/(good+errors)*100:.2f}% of a total of {good+errors} parishes')